// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Foxoft.Models;

namespace Foxoft.Migrations
{
    [DbContext(typeof(subContext))]
    [Migration("20220226074626_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Foxoft.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("GetPrint")
                        .HasColumnType("bit");

                    b.Property<string>("GridViewLayout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintDesignPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrinterCopyNum")
                        .HasColumnType("int");

                    b.Property<string>("PrinterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GetPrint = false,
                            GridViewLayout = @"<XtraSerializer version=""1.0"" application=""View"">
  <property name=""#LayoutVersion"" />
  <property name=""#LayoutScaleFactor"">@1,Width=1@1,Height=1</property>
  <property name=""Appearance"" isnull=""true"" iskey=""true"">
    <property name=""Row"" iskey=""true"" value=""Row"">
      <property name=""Options"" isnull=""true"" iskey=""true"">
        <property name=""UseFont"">true</property>
      </property>
      <property name=""Font"">Tahoma, 12pt</property>
    </property>
    <property name=""FooterPanel"" iskey=""true"" value=""FooterPanel"">
      <property name=""Options"" isnull=""true"" iskey=""true"">
        <property name=""UseFont"">true</property>
      </property>
      <property name=""Font"">Tahoma, 12pt</property>
    </property>
  </property>
  <property name=""OptionsBehavior"" isnull=""true"" iskey=""true"">
    <property name=""Editable"">false</property>
  </property>
  <property name=""OptionsView"" isnull=""true"" iskey=""true"">
    <property name=""ColumnHeaderAutoHeight"">True</property>
    <property name=""ShowAutoFilterRow"">true</property>
    <property name=""ShowGroupPanel"">false</property>
    <property name=""ShowIndicator"">false</property>
  </property>
  <property name=""FixedLineWidth"">2</property>
  <property name=""IndicatorWidth"">-1</property>
  <property name=""ColumnPanelRowHeight"">-1</property>
  <property name=""RowSeparatorHeight"">0</property>
  <property name=""FooterPanelHeight"">-1</property>
  <property name=""HorzScrollVisibility"">Auto</property>
  <property name=""VertScrollVisibility"">Auto</property>
  <property name=""RowHeight"">-1</property>
  <property name=""GroupRowHeight"">-1</property>
  <property name=""GroupFormat"">{0}: [#image]{1} {2}</property>
  <property name=""ChildGridLevelName"" />
  <property name=""VertScrollTipFieldName"" />
  <property name=""PreviewFieldName"" />
  <property name=""GroupPanelText"" />
  <property name=""NewItemRowText"" />
  <property name=""LevelIndent"">-1</property>
  <property name=""PreviewIndent"">-1</property>
  <property name=""PreviewLineCount"">-1</property>
  <property name=""ScrollStyle"">LiveVertScroll, LiveHorzScroll</property>
  <property name=""FocusRectStyle"">CellFocus</property>
  <property name=""HorzScrollStep"">0</property>
  <property name=""ActiveFilterEnabled"">true</property>
  <property name=""ViewCaptionHeight"">-1</property>
  <property name=""Columns"" iskey=""true"" value=""0"" />
  <property name=""ViewCaption"" />
  <property name=""BorderStyle"">Default</property>
  <property name=""SynchronizeClones"">true</property>
  <property name=""DetailTabHeaderLocation"">Top</property>
  <property name=""Name"">gridView1</property>
  <property name=""DetailHeight"">350</property>
  <property name=""Tag"" isnull=""true"" />
  <property name=""GroupSummary"" iskey=""true"" value=""0"" />
  <property name=""ActiveFilterString"" />
  <property name=""FormatRules"" iskey=""true"" value=""0"" />
  <property name=""FormatConditions"" iskey=""true"" value=""0"" />
  <property name=""GroupSummarySortInfoState"" />
  <property name=""FindFilterText"" />
  <property name=""FindPanelVisible"">false</property>
</XtraSerializer>",
                            PrinterCopyNum = 0
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcClaim", b =>
                {
                    b.Property<string>("ClaimCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaimDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaimCode");

                    b.ToTable("DcClaims");

                    b.HasData(
                        new
                        {
                            ClaimCode = "PosDiscount",
                            ClaimDesc = "POS Endirimi"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcCurrAcc", b =>
                {
                    b.Property<string>("CurrAccCode")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Address")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("BirthDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateTime(1901, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("BonusCardNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(50);

                    b.Property<byte>("CompanyCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<decimal>("CreditLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("0");

                    b.Property<byte>("CurrAccTypeCode")
                        .HasColumnType("tinyint");

                    b.Property<double>("CustomerPosDiscountRate")
                        .HasColumnType("float");

                    b.Property<byte>("CustomerTypeCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("DataLanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(5);

                    b.Property<string>("FatherName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(60)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(60);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(60)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(60);

                    b.Property<string>("IdentityNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(20);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVip")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsVIP")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("LastName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(60)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("NewPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(5);

                    b.Property<string>("PhoneNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(150);

                    b.Property<Guid>("RowGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(20);

                    b.Property<byte>("VendorTypeCode")
                        .HasColumnType("tinyint");

                    b.HasKey("CurrAccCode");

                    b.HasIndex("CurrAccTypeCode")
                        .HasName("IX_CurrAccTypeCode");

                    b.ToTable("DcCurrAccs");

                    b.HasData(
                        new
                        {
                            CurrAccCode = "CA-1",
                            CompanyCode = (byte)0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditLimit = 0m,
                            CurrAccTypeCode = (byte)1,
                            CustomerPosDiscountRate = 0.0,
                            CustomerTypeCode = (byte)0,
                            FirstName = "Sübhan",
                            IsDisabled = false,
                            IsVip = false,
                            LastName = "Hüseynzadə",
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewPassword = "123",
                            PhoneNum = "0519678909",
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorTypeCode = (byte)0
                        },
                        new
                        {
                            CurrAccCode = "CA-2",
                            CompanyCode = (byte)0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditLimit = 0m,
                            CurrAccTypeCode = (byte)2,
                            CustomerPosDiscountRate = 0.0,
                            CustomerTypeCode = (byte)0,
                            FirstName = "Orxan",
                            IsDisabled = false,
                            IsVip = false,
                            LastName = "Sederek",
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewPassword = "456",
                            PhoneNum = "0773628800",
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorTypeCode = (byte)0
                        },
                        new
                        {
                            CurrAccCode = "CA-3",
                            CompanyCode = (byte)0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditLimit = 0m,
                            CurrAccTypeCode = (byte)3,
                            CustomerPosDiscountRate = 0.0,
                            CustomerTypeCode = (byte)0,
                            FirstName = "Vagif",
                            IsDisabled = false,
                            IsVip = false,
                            LastName = "Mustafayev",
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewPassword = "456",
                            PhoneNum = "0553628804",
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000"),
                            VendorTypeCode = (byte)0
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcCurrAccType", b =>
                {
                    b.Property<byte>("CurrAccTypeCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("CurrAccTypeDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(100);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("RowGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrAccTypeCode");

                    b.ToTable("DcCurrAccTypes");

                    b.HasData(
                        new
                        {
                            CurrAccTypeCode = (byte)1,
                            CurrAccTypeDescription = "Müştəri",
                            IsDisabled = false,
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CurrAccTypeCode = (byte)2,
                            CurrAccTypeDescription = "Tədarikçi",
                            IsDisabled = false,
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CurrAccTypeCode = (byte)3,
                            CurrAccTypeDescription = "Personal",
                            IsDisabled = false,
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DcFeatures");
                });

            modelBuilder.Entity("Foxoft.Models.DcOffice", b =>
                {
                    b.Property<string>("OfficeCode")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<decimal>("CompanyCode")
                        .HasColumnType("numeric(4, 0)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("OfficeDesc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(150);

                    b.Property<Guid>("RowGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OfficeCode");

                    b.ToTable("DcOffices");

                    b.HasData(
                        new
                        {
                            OfficeCode = "OFS01",
                            CompanyCode = 0m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OfficeDesc = "Bakıxanov Ofisi",
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OfficeCode = "OFS02",
                            CompanyCode = 0m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OfficeDesc = "Elmlər Ofisi",
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcPaymentType", b =>
                {
                    b.Property<byte>("PaymentTypeCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("PaymentTypeDesc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(100);

                    b.HasKey("PaymentTypeCode");

                    b.ToTable("DcPaymentTypes");

                    b.HasData(
                        new
                        {
                            PaymentTypeCode = (byte)1,
                            PaymentTypeDesc = "Nağd"
                        },
                        new
                        {
                            PaymentTypeCode = (byte)2,
                            PaymentTypeDesc = "Visa"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcProcess", b =>
                {
                    b.Property<string>("ProcessCode")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("ProcessDescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(150);

                    b.HasKey("ProcessCode");

                    b.ToTable("DcProcesses");

                    b.HasData(
                        new
                        {
                            ProcessCode = "RS",
                            ProcessDescription = "Pərakəndə Satış"
                        },
                        new
                        {
                            ProcessCode = "RP",
                            ProcessDescription = "Pərakəndə Alış"
                        },
                        new
                        {
                            ProcessCode = "P",
                            ProcessDescription = "Ödəmə"
                        },
                        new
                        {
                            ProcessCode = "SB",
                            ProcessDescription = "Toptan Alış"
                        },
                        new
                        {
                            ProcessCode = "W",
                            ProcessDescription = "Toptan Satış"
                        },
                        new
                        {
                            ProcessCode = "EX",
                            ProcessDescription = "Xərclər"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcProduct", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<double>("PosDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(150);

                    b.Property<byte>("ProductTypeCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("PromotionCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(50);

                    b.Property<string>("PromotionCode2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(50);

                    b.Property<double>("PurchasePrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.Property<double>("RetailPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.Property<double>("TaxRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("UseInternet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("UsePos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<double>("WholesalePrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.HasKey("ProductCode");

                    b.HasIndex("ProductTypeCode")
                        .HasName("IX_ProductTypeCode");

                    b.ToTable("DcProducts");

                    b.HasData(
                        new
                        {
                            ProductCode = "test01",
                            Barcode = "123456",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosDiscount = 0.0,
                            ProductDescription = "Papaq",
                            ProductTypeCode = (byte)1,
                            PurchasePrice = 0.0,
                            RetailPrice = 4.5,
                            TaxRate = 0.0,
                            UseInternet = false,
                            UsePos = false,
                            WholesalePrice = 0.0
                        },
                        new
                        {
                            ProductCode = "test02",
                            Barcode = "2000000000013",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosDiscount = 0.0,
                            ProductDescription = "Salvar",
                            ProductTypeCode = (byte)1,
                            PurchasePrice = 0.0,
                            RetailPrice = 2.5,
                            TaxRate = 0.0,
                            UseInternet = false,
                            UsePos = false,
                            WholesalePrice = 0.0
                        },
                        new
                        {
                            ProductCode = "xerc01",
                            Barcode = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosDiscount = 0.0,
                            ProductDescription = "Yol Xerci",
                            ProductTypeCode = (byte)2,
                            PurchasePrice = 0.0,
                            RetailPrice = 0.0,
                            TaxRate = 0.0,
                            UseInternet = false,
                            UsePos = false,
                            WholesalePrice = 0.0
                        },
                        new
                        {
                            ProductCode = "xerc02",
                            Barcode = "",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PosDiscount = 0.0,
                            ProductDescription = "Isiq Pulu",
                            ProductTypeCode = (byte)2,
                            PurchasePrice = 0.0,
                            RetailPrice = 0.0,
                            TaxRate = 0.0,
                            UseInternet = false,
                            UsePos = false,
                            WholesalePrice = 0.0
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcProductType", b =>
                {
                    b.Property<byte>("ProductTypeCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProductTypeDesc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(50);

                    b.HasKey("ProductTypeCode");

                    b.ToTable("DcProductTypes");

                    b.HasData(
                        new
                        {
                            ProductTypeCode = (byte)1,
                            ProductTypeDesc = "Məhsul"
                        },
                        new
                        {
                            ProductTypeCode = (byte)2,
                            ProductTypeDesc = "Xərc"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("ReportFilter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportLayout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportQuery")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DcReports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01fdab8b-0c03-4bdb-bc07-c03ff743ce45"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReportName = "Satis",
                            ReportQuery = "select * from TrInvoiceLines"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcRole", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("RoleDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleCode");

                    b.ToTable("DcRoles");

                    b.HasData(
                        new
                        {
                            RoleCode = "Admin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleDesc = "Administrator"
                        },
                        new
                        {
                            RoleCode = "MGZ",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleDesc = "Mağaza İstifadəçisi"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcStore", b =>
                {
                    b.Property<string>("StoreCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("CompanyCode")
                        .HasColumnType("numeric(4, 0)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<Guid>("RowGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StoreDesc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(150);

                    b.HasKey("StoreCode");

                    b.ToTable("DcStores");

                    b.HasData(
                        new
                        {
                            StoreCode = "mgz-01",
                            CompanyCode = 0m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000"),
                            StoreDesc = "Bakıxanov"
                        },
                        new
                        {
                            StoreCode = "mgz-02",
                            CompanyCode = 0m,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000"),
                            StoreDesc = "Elmlər"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcTerminal", b =>
                {
                    b.Property<string>("TerminalCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<Guid>("RowGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TerminalDesc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(150);

                    b.HasKey("TerminalCode");

                    b.ToTable("DcTerminals");
                });

            modelBuilder.Entity("Foxoft.Models.DcVariable", b =>
                {
                    b.Property<string>("VariableCode")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<int?>("LastNumber")
                        .HasColumnType("int");

                    b.Property<string>("VariableDesc")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("VariableCode");

                    b.ToTable("DcVariables");

                    b.HasData(
                        new
                        {
                            VariableCode = "CA",
                            VariableDesc = "Cari"
                        },
                        new
                        {
                            VariableCode = "PR",
                            VariableDesc = "Məhsul"
                        },
                        new
                        {
                            VariableCode = "RS",
                            VariableDesc = "Pərakəndə Satış"
                        },
                        new
                        {
                            VariableCode = "RP",
                            VariableDesc = "Pərakəndə Alış"
                        },
                        new
                        {
                            VariableCode = "P",
                            VariableDesc = "Ödəmə"
                        },
                        new
                        {
                            VariableCode = "SB",
                            VariableDesc = "Toptan Alış"
                        },
                        new
                        {
                            VariableCode = "W",
                            VariableDesc = "Toptan Satış"
                        },
                        new
                        {
                            VariableCode = "EX",
                            VariableDesc = "Xərclər"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.DcWarehouse", b =>
                {
                    b.Property<string>("WarehouseCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("ControlStockLevel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("OfficeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(5);

                    b.Property<bool>("PermitNegativeStock")
                        .HasColumnType("bit");

                    b.Property<Guid>("RowGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(50);

                    b.Property<string>("WarehouseDesc")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(150);

                    b.Property<byte>("WarehouseTypeCode")
                        .HasColumnType("tinyint");

                    b.Property<bool>("WarnNegativeStock")
                        .HasColumnType("bit");

                    b.Property<bool>("WarnStockLevelRate")
                        .HasColumnType("bit");

                    b.HasKey("WarehouseCode");

                    b.ToTable("DcWarehouses");

                    b.HasData(
                        new
                        {
                            WarehouseCode = "depo-01",
                            ControlStockLevel = false,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDefault = false,
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermitNegativeStock = false,
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000"),
                            WarehouseDesc = "Bakıxanov deposu",
                            WarehouseTypeCode = (byte)0,
                            WarnNegativeStock = false,
                            WarnStockLevelRate = false
                        },
                        new
                        {
                            WarehouseCode = "depo-02",
                            ControlStockLevel = false,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDefault = false,
                            IsDisabled = false,
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermitNegativeStock = false,
                            RowGuid = new Guid("00000000-0000-0000-0000-000000000000"),
                            WarehouseDesc = "Elmlər deposu",
                            WarehouseTypeCode = (byte)0,
                            WarnNegativeStock = false,
                            WarnStockLevelRate = false
                        });
                });

            modelBuilder.Entity("Foxoft.Models.MigrationHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("ContextKey")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<byte[]>("Model")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("MigrationId", "ContextKey")
                        .HasName("PK_dbo.__MigrationHistory");

                    b.ToTable("__MigrationHistory");
                });

            modelBuilder.Entity("Foxoft.Models.Sysdiagrams", b =>
                {
                    b.Property<int>("DiagramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("diagram_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Definition")
                        .HasColumnName("definition")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("PrincipalId")
                        .HasColumnName("principal_id")
                        .HasColumnType("int");

                    b.Property<int?>("Version")
                        .HasColumnName("version")
                        .HasColumnType("int");

                    b.HasKey("DiagramId")
                        .HasName("PK_dbo.sysdiagrams");

                    b.ToTable("sysdiagrams");
                });

            modelBuilder.Entity("Foxoft.Models.TrCurrAccRole", b =>
                {
                    b.Property<int>("CurrAccRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("CurrAccCode")
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("RoleCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CurrAccRoleId");

                    b.HasIndex("CurrAccCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("TrCurrAccRoles");

                    b.HasData(
                        new
                        {
                            CurrAccRoleId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrAccCode = "CA-1",
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleCode = "Admin"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.TrFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.HasIndex("FeatureId", "ProductCode")
                        .IsUnique()
                        .HasFilter("[ProductCode] IS NOT NULL");

                    b.ToTable("TrFeatures");
                });

            modelBuilder.Entity("Foxoft.Models.TrInvoiceHeader", b =>
                {
                    b.Property<Guid>("InvoiceHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("CurrAccCode")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("CustomsDocumentNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("DocumentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.Property<TimeSpan>("DocumentTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time(0)")
                        .HasDefaultValueSql("convert(varchar(10), GETDATE(), 108)");

                    b.Property<byte>("FiscalPrintedState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("space(0)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("IsPrinted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("IsReturn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("IsSalesViaInternet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("OperationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<TimeSpan>("OperationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time(0)")
                        .HasDefaultValueSql("convert(varchar(10), GETDATE(), 108)");

                    b.Property<string>("PosTerminalId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(5);

                    b.Property<Guid?>("RelatedInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.HasKey("InvoiceHeaderId");

                    b.HasIndex("CurrAccCode")
                        .HasName("IX_CurrAccCode");

                    b.ToTable("TrInvoiceHeaders");
                });

            modelBuilder.Entity("Foxoft.Models.TrInvoiceLine", b =>
                {
                    b.Property<Guid>("InvoiceLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("CurrencyCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.Property<decimal>("DiscountCampaign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("0");

                    b.Property<double>("ExchangeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("InvoiceHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("LineDescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(100);

                    b.Property<decimal>("NetAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PosDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("0");

                    b.Property<double>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<Guid?>("RelatedLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SalesPersonCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(50);

                    b.Property<float>("VatRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValueSql("0");

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceHeaderId")
                        .HasName("IX_InvoiceHeaderId");

                    b.HasIndex("ProductCode")
                        .HasName("IX_ProductCode");

                    b.ToTable("TrInvoiceLines");
                });

            modelBuilder.Entity("Foxoft.Models.TrPaymentHeader", b =>
                {
                    b.Property<Guid>("PaymentHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompanyCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("CurrAccCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValueSql("convert(varchar(10), GETDATE(), 108)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("DocumentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DocumentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("space(0)");

                    b.Property<TimeSpan>("DocumentTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time(0)")
                        .HasDefaultValueSql("convert(varchar(10), GETDATE(), 108)");

                    b.Property<double>("ExchangeRate")
                        .HasColumnType("float")
                        .HasMaxLength(60);

                    b.Property<Guid?>("InvoiceHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("space(0)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(5);

                    b.Property<short>("PosterminalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("space(0)");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.HasKey("PaymentHeaderId");

                    b.HasIndex("InvoiceHeaderId");

                    b.ToTable("TrPaymentHeaders");
                });

            modelBuilder.Entity("Foxoft.Models.TrPaymentLine", b =>
                {
                    b.Property<Guid>("PaymentLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("BankId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.Property<double>("ExchangeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("LineDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Payment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("PaymentHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("PaymentTypeCode")
                        .HasColumnType("tinyint");

                    b.HasKey("PaymentLineId");

                    b.HasIndex("PaymentHeaderId");

                    b.HasIndex("PaymentTypeCode");

                    b.ToTable("TrPaymentLines");
                });

            modelBuilder.Entity("Foxoft.Models.TrRoleClaim", b =>
                {
                    b.Property<int>("RoleClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleClaimId");

                    b.HasIndex("ClaimCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("TrRoleClaims");

                    b.HasData(
                        new
                        {
                            RoleClaimId = 1,
                            ClaimCode = "PosDiscount",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleCode = "Admin"
                        });
                });

            modelBuilder.Entity("Foxoft.Models.TrShipmentHeader", b =>
                {
                    b.Property<Guid>("ShipmentHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompanyCode")
                        .HasColumnType("decimal(18,2)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("CurrAccCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("CustomsDocumentNumber")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(200);

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrderBase")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTransferApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("OperationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<TimeSpan>("OperationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time(0)")
                        .HasDefaultValueSql("convert(varchar(10), GETDATE(), 108)");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(5);

                    b.Property<byte>("ShipTypeCode")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ShippingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ShippingNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.Property<Guid?>("ShippingPostalAddressId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(60);

                    b.Property<TimeSpan>("ShippingTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time(0)")
                        .HasDefaultValueSql("convert(varchar(10), GETDATE(), 108)");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.Property<string>("ToWarehouseCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("TransferApprovedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("space(0)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(30);

                    b.HasKey("ShipmentHeaderId");

                    b.ToTable("TrShipmentHeaders");
                });

            modelBuilder.Entity("Foxoft.Models.TrShipmentLine", b =>
                {
                    b.Property<Guid>("ShipmentLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdatedUserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("substring(suser_name(),patindex('%\\%',suser_name())+(1),(20))")
                        .HasMaxLength(20);

                    b.Property<string>("LineDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<string>("ProductCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("space(0)");

                    b.Property<string>("ProductDimensionCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("SalespersonCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.Property<Guid>("ShipmentHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("UsedBarcode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("space(0)")
                        .HasMaxLength(10);

                    b.HasKey("ShipmentLineId");

                    b.HasIndex("ShipmentHeaderId")
                        .HasName("IX_ShipmentHeaderID");

                    b.ToTable("TrShipmentLines");
                });

            modelBuilder.Entity("Foxoft.Models.DcCurrAcc", b =>
                {
                    b.HasOne("Foxoft.Models.DcCurrAccType", "DcCurrAccType")
                        .WithMany("DcCurrAccs")
                        .HasForeignKey("CurrAccTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foxoft.Models.DcProduct", b =>
                {
                    b.HasOne("Foxoft.Models.DcProductType", "DcProductType")
                        .WithMany("DcProducts")
                        .HasForeignKey("ProductTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foxoft.Models.TrCurrAccRole", b =>
                {
                    b.HasOne("Foxoft.Models.DcCurrAcc", "DcCurrAcc")
                        .WithMany("TrCurrAccRole")
                        .HasForeignKey("CurrAccCode");

                    b.HasOne("Foxoft.Models.DcRole", "DcRole")
                        .WithMany("TrCurrAccRoles")
                        .HasForeignKey("RoleCode");
                });

            modelBuilder.Entity("Foxoft.Models.TrFeature", b =>
                {
                    b.HasOne("Foxoft.Models.DcFeature", "DcFeature")
                        .WithMany("TrFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foxoft.Models.DcProduct", "DcProduct")
                        .WithMany("TrFeature")
                        .HasForeignKey("ProductCode");
                });

            modelBuilder.Entity("Foxoft.Models.TrInvoiceHeader", b =>
                {
                    b.HasOne("Foxoft.Models.DcCurrAcc", "DcCurrAcc")
                        .WithMany("TrInvoiceHeaders")
                        .HasForeignKey("CurrAccCode");
                });

            modelBuilder.Entity("Foxoft.Models.TrInvoiceLine", b =>
                {
                    b.HasOne("Foxoft.Models.TrInvoiceHeader", "TrInvoiceHeader")
                        .WithMany("TrInvoiceLines")
                        .HasForeignKey("InvoiceHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foxoft.Models.DcProduct", "DcProduct")
                        .WithMany("TrInvoiceLines")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foxoft.Models.TrPaymentHeader", b =>
                {
                    b.HasOne("Foxoft.Models.TrInvoiceHeader", "TrInvoiceHeader")
                        .WithMany("TrPaymentHeaders")
                        .HasForeignKey("InvoiceHeaderId");
                });

            modelBuilder.Entity("Foxoft.Models.TrPaymentLine", b =>
                {
                    b.HasOne("Foxoft.Models.TrPaymentHeader", "TrPaymentHeader")
                        .WithMany("TrPaymentLines")
                        .HasForeignKey("PaymentHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foxoft.Models.DcPaymentType", "DcPaymentType")
                        .WithMany("TrPaymentLines")
                        .HasForeignKey("PaymentTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foxoft.Models.TrRoleClaim", b =>
                {
                    b.HasOne("Foxoft.Models.DcClaim", "DcClaim")
                        .WithMany("TrRoleClaims")
                        .HasForeignKey("ClaimCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foxoft.Models.DcRole", "DcRole")
                        .WithMany("TrRoleClaims")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foxoft.Models.TrShipmentLine", b =>
                {
                    b.HasOne("Foxoft.Models.TrShipmentHeader", "TrShipmentHeader")
                        .WithMany("TrShipmentLines")
                        .HasForeignKey("ShipmentHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
