//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxoft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foxoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Common_Attention {
            get {
                return ResourceManager.GetString("Common_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}.
        /// </summary>
        public static string Common_ErrorTitle {
            get {
                return ResourceManager.GetString("Common_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Mode.
        /// </summary>
        public static string Common_InputMode {
            get {
                return ResourceManager.GetString("Common_InputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Mode.
        /// </summary>
        public static string Common_MouseMode {
            get {
                return ResourceManager.GetString("Common_MouseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Program.
        /// </summary>
        public static string Common_QuitProgram {
            get {
                return ResourceManager.GetString("Common_QuitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Mode.
        /// </summary>
        public static string Common_SensorMode {
            get {
                return ResourceManager.GetString("Common_SensorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Common_Theme {
            get {
                return ResourceManager.GetString("Common_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Print.
        /// </summary>
        public static string Entity_AppSetting_AutoPrint {
            get {
                return ResourceManager.GetString("Entity_AppSetting_AutoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save.
        /// </summary>
        public static string Entity_AppSetting_AutoSave {
            get {
                return ResourceManager.GetString("Entity_AppSetting_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Unit of MeasureId.
        /// </summary>
        public static string Entity_AppSetting_DefaultUnitOfMeasureId {
            get {
                return ResourceManager.GetString("Entity_AppSetting_DefaultUnitOfMeasureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string Entity_AppSetting_DueDate {
            get {
                return ResourceManager.GetString("Entity_AppSetting_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridView Layout.
        /// </summary>
        public static string Entity_AppSetting_GridViewLayout {
            get {
                return ResourceManager.GetString("Entity_AppSetting_GridViewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Edit Grace Days.
        /// </summary>
        public static string Entity_AppSetting_InvoiceEditGraceDays {
            get {
                return ResourceManager.GetString("Entity_AppSetting_InvoiceEditGraceDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Entity_AppSetting_License {
            get {
                return ResourceManager.GetString("Entity_AppSetting_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Code.
        /// </summary>
        public static string Entity_AppSetting_LocalCurrencyCode {
            get {
                return ResourceManager.GetString("Entity_AppSetting_LocalCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize Database Indexes ({0}%).
        /// </summary>
        public static string Entity_AppSetting_OptimizeDatabaseIndexes {
            get {
                return ResourceManager.GetString("Entity_AppSetting_OptimizeDatabaseIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Edit Grace Days.
        /// </summary>
        public static string Entity_AppSetting_PaymentEditGraceDays {
            get {
                return ResourceManager.GetString("Entity_AppSetting_PaymentEditGraceDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Count.
        /// </summary>
        public static string Entity_AppSetting_PrintCount {
            get {
                return ResourceManager.GetString("Entity_AppSetting_PrintCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Design Path.
        /// </summary>
        public static string Entity_AppSetting_PrintDesignPath {
            get {
                return ResourceManager.GetString("Entity_AppSetting_PrintDesignPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Name.
        /// </summary>
        public static string Entity_AppSetting_PrinterName {
            get {
                return ResourceManager.GetString("Entity_AppSetting_PrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Barcode.
        /// </summary>
        public static string Entity_AppSetting_UseBarcode {
            get {
                return ResourceManager.GetString("Entity_AppSetting_UseBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Price List.
        /// </summary>
        public static string Entity_AppSetting_UsePriceList {
            get {
                return ResourceManager.GetString("Entity_AppSetting_UsePriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Scales.
        /// </summary>
        public static string Entity_AppSetting_UseScales {
            get {
                return ResourceManager.GetString("Entity_AppSetting_UseScales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp Chrome Profile Name.
        /// </summary>
        public static string Entity_AppSetting_WhatsappChromeProfileName {
            get {
                return ResourceManager.GetString("Entity_AppSetting_WhatsappChromeProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string ERP_ACE_AppSettings {
            get {
                return ResourceManager.GetString("ERP_ACE_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Transfer.
        /// </summary>
        public static string ERP_ACE_CashTransfers {
            get {
                return ResourceManager.GetString("ERP_ACE_CashTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count In.
        /// </summary>
        public static string ERP_ACE_CountInInvoice {
            get {
                return ResourceManager.GetString("ERP_ACE_CountInInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Out.
        /// </summary>
        public static string ERP_ACE_CountOutInvoice {
            get {
                return ResourceManager.GetString("ERP_ACE_CountOutInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrAcc Feature Type.
        /// </summary>
        public static string ERP_ACE_CurrAccFeatureType {
            get {
                return ResourceManager.GetString("ERP_ACE_CurrAccFeatureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Account.
        /// </summary>
        public static string ERP_ACE_CurrAccs {
            get {
                return ResourceManager.GetString("ERP_ACE_CurrAccs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string ERP_ACE_Expenses {
            get {
                return ResourceManager.GetString("ERP_ACE_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string ERP_ACE_Favorites {
            get {
                return ResourceManager.GetString("ERP_ACE_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installmentsale Invoice.
        /// </summary>
        public static string ERP_ACE_InstallmentsaleInvoice {
            get {
                return ResourceManager.GetString("ERP_ACE_InstallmentsaleInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installmentsale Return.
        /// </summary>
        public static string ERP_ACE_InstallmentsaleReturn {
            get {
                return ResourceManager.GetString("ERP_ACE_InstallmentsaleReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installmentsale Return Custom.
        /// </summary>
        public static string ERP_ACE_InstallmentSaleReturnCustom {
            get {
                return ResourceManager.GetString("ERP_ACE_InstallmentSaleReturnCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Sales.
        /// </summary>
        public static string ERP_ACE_InstallmentSales {
            get {
                return ResourceManager.GetString("ERP_ACE_InstallmentSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Count.
        /// </summary>
        public static string ERP_ACE_InventoryCount {
            get {
                return ResourceManager.GetString("ERP_ACE_InventoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Transfer.
        /// </summary>
        public static string ERP_ACE_InventoryTransfers {
            get {
                return ResourceManager.GetString("ERP_ACE_InventoryTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string ERP_ACE_Invoices {
            get {
                return ResourceManager.GetString("ERP_ACE_Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string ERP_ACE_Operations {
            get {
                return ResourceManager.GetString("ERP_ACE_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string ERP_ACE_Parameters {
            get {
                return ResourceManager.GetString("ERP_ACE_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Detail.
        /// </summary>
        public static string ERP_ACE_PaymentDetail {
            get {
                return ResourceManager.GetString("ERP_ACE_PaymentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List.
        /// </summary>
        public static string ERP_ACE_PriceList {
            get {
                return ResourceManager.GetString("ERP_ACE_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Discounts.
        /// </summary>
        public static string ERP_ACE_ProductDiscounts {
            get {
                return ResourceManager.GetString("ERP_ACE_ProductDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature Type.
        /// </summary>
        public static string ERP_ACE_ProductFeatureType {
            get {
                return ResourceManager.GetString("ERP_ACE_ProductFeatureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ERP_ACE_Products {
            get {
                return ResourceManager.GetString("ERP_ACE_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ERP_ACE_Reports {
            get {
                return ResourceManager.GetString("ERP_ACE_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Purchase Invoice.
        /// </summary>
        public static string ERP_ACE_RetailPurchaseInvoice {
            get {
                return ResourceManager.GetString("ERP_ACE_RetailPurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Purchase Order.
        /// </summary>
        public static string ERP_ACE_RetailPurchaseOrder {
            get {
                return ResourceManager.GetString("ERP_ACE_RetailPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Purchase Return.
        /// </summary>
        public static string ERP_ACE_RetailPurchaseReturn {
            get {
                return ResourceManager.GetString("ERP_ACE_RetailPurchaseReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return Custom.
        /// </summary>
        public static string ERP_ACE_RetailPurchaseReturnCustom {
            get {
                return ResourceManager.GetString("ERP_ACE_RetailPurchaseReturnCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailsale Invoice.
        /// </summary>
        public static string ERP_ACE_RetailSaleInvoice {
            get {
                return ResourceManager.GetString("ERP_ACE_RetailSaleInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailsale Order.
        /// </summary>
        public static string ERP_ACE_RetailSaleOrder {
            get {
                return ResourceManager.GetString("ERP_ACE_RetailSaleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailsale Return.
        /// </summary>
        public static string ERP_ACE_RetailSaleReturn {
            get {
                return ResourceManager.GetString("ERP_ACE_RetailSaleReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailsale Return Custom.
        /// </summary>
        public static string ERP_ACE_RetailSaleReturnCustom {
            get {
                return ResourceManager.GetString("ERP_ACE_RetailSaleReturnCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store List.
        /// </summary>
        public static string ERP_ACE_StoreList {
            get {
                return ResourceManager.GetString("ERP_ACE_StoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string ERP_ACE_Users {
            get {
                return ResourceManager.GetString("ERP_ACE_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill.
        /// </summary>
        public static string ERP_ACE_Waybill {
            get {
                return ResourceManager.GetString("ERP_ACE_Waybill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill In.
        /// </summary>
        public static string ERP_ACE_WaybillIn {
            get {
                return ResourceManager.GetString("ERP_ACE_WaybillIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill Out.
        /// </summary>
        public static string ERP_ACE_WaybillOut {
            get {
                return ResourceManager.GetString("ERP_ACE_WaybillOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Invoice.
        /// </summary>
        public static string ERP_ACE_WholeSaleInvoice {
            get {
                return ResourceManager.GetString("ERP_ACE_WholeSaleInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Return.
        /// </summary>
        public static string ERP_ACE_WholeSaleReturn {
            get {
                return ResourceManager.GetString("ERP_ACE_WholeSaleReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Return Custom.
        /// </summary>
        public static string ERP_ACE_WholeSaleReturnCustom {
            get {
                return ResourceManager.GetString("ERP_ACE_WholeSaleReturnCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string ERP_AddToFavorites {
            get {
                return ResourceManager.GetString("ERP_AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Users.
        /// </summary>
        public static string ERP_BBI_ActiveUsers {
            get {
                return ResourceManager.GetString("ERP_BBI_ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Windows.
        /// </summary>
        public static string ERP_BBI_ActiveWindows {
            get {
                return ResourceManager.GetString("ERP_BBI_ActiveWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User.
        /// </summary>
        public static string ERP_BBI_ChangeUser {
            get {
                return ResourceManager.GetString("ERP_BBI_ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Windows.
        /// </summary>
        public static string ERP_BBI_CloseWindows {
            get {
                return ResourceManager.GetString("ERP_BBI_CloseWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string ERP_BSI_Reports {
            get {
                return ResourceManager.GetString("ERP_BSI_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Register.
        /// </summary>
        public static string ERP_CashRegs {
            get {
                return ResourceManager.GetString("ERP_CashRegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching constructor found for {0}.
        /// </summary>
        public static string ERP_NoMatchingCtor {
            get {
                return ResourceManager.GetString("ERP_NoMatchingCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be opened: {1}.
        /// </summary>
        public static string ERP_OpenFormError {
            get {
                return ResourceManager.GetString("ERP_OpenFormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Favorites.
        /// </summary>
        public static string ERP_RemoveFromFavorites {
            get {
                return ResourceManager.GetString("ERP_RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string ERP_RibbonPage_Control {
            get {
                return ResourceManager.GetString("ERP_RibbonPage_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ERP_RibbonPage_Home {
            get {
                return ResourceManager.GetString("ERP_RibbonPage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        public static string Login_POS {
            get {
                return ResourceManager.GetString("Login_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap startup550x363_png {
            get {
                object obj = ResourceManager.GetObject("startup550x363.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
