using Foxoft.Properties;

namespace Foxoft
{
    partial class FormWarehouse
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            btn_Cancel = new DevExpress.XtraEditors.SimpleButton();
            btn_Ok = new DevExpress.XtraEditors.SimpleButton();
            WarehouseCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            dcWarehousesBindingSource = new BindingSource(components);
            WarehouseDescTextEdit = new DevExpress.XtraEditors.TextEdit();
            WarehouseTypeCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            OfficeCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            StoreCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            PermitNegativeStockCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            WarnNegativeStockCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            ControlStockLevelCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            WarnStockLevelRateCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            IsDefaultCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            IsDisabledCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            Root = new DevExpress.XtraLayout.LayoutControlGroup();
            autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            ItemForWarehouseCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForStoreCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForWarehouseTypeCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForWarehouseDesc = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForOfficeCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForPermitNegativeStock = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForWarnNegativeStock = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForControlStockLevel = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForWarnStockLevelRate = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlGroup3 = new DevExpress.XtraLayout.LayoutControlGroup();
            ItemForIsDefault = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForIsDisabled = new DevExpress.XtraLayout.LayoutControlItem();
            emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).BeginInit();
            dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)WarehouseCodeTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dcWarehousesBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)WarehouseDescTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)WarehouseTypeCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)OfficeCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)StoreCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)PermitNegativeStockCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)WarnNegativeStockCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ControlStockLevelCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)WarnStockLevelRateCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)IsDefaultCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)IsDisabledCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)Root).BeginInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarehouseCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForStoreCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarehouseTypeCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarehouseDesc).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForOfficeCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPermitNegativeStock).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarnNegativeStock).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForControlStockLevel).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarnStockLevelRate).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlGroup3).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDefault).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDisabled).BeginInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).BeginInit();
            SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            dataLayoutControl1.Controls.Add(btn_Cancel);
            dataLayoutControl1.Controls.Add(btn_Ok);
            dataLayoutControl1.Controls.Add(WarehouseCodeTextEdit);
            dataLayoutControl1.Controls.Add(WarehouseDescTextEdit);
            dataLayoutControl1.Controls.Add(WarehouseTypeCodeLookUpEdit);
            dataLayoutControl1.Controls.Add(OfficeCodeLookUpEdit);
            dataLayoutControl1.Controls.Add(StoreCodeLookUpEdit);
            dataLayoutControl1.Controls.Add(PermitNegativeStockCheckEdit);
            dataLayoutControl1.Controls.Add(WarnNegativeStockCheckEdit);
            dataLayoutControl1.Controls.Add(ControlStockLevelCheckEdit);
            dataLayoutControl1.Controls.Add(WarnStockLevelRateCheckEdit);
            dataLayoutControl1.Controls.Add(IsDefaultCheckEdit);
            dataLayoutControl1.Controls.Add(IsDisabledCheckEdit);
            dataLayoutControl1.DataSource = dcWarehousesBindingSource;
            dataLayoutControl1.Dock = DockStyle.Fill;
            dataLayoutControl1.Location = new Point(0, 0);
            dataLayoutControl1.Name = "dataLayoutControl1";
            dataLayoutControl1.OptionsFocus.MoveFocusRightToLeft = false;
            dataLayoutControl1.Root = Root;
            dataLayoutControl1.Size = new Size(604, 300);
            dataLayoutControl1.TabIndex = 0;
            dataLayoutControl1.Text = "dataLayoutControl1";
            dataLayoutControl1.FieldRetrieving += dataLayoutControl1_FieldRetrieving;
            // 
            // btn_Cancel
            // 
            btn_Cancel.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Cancel.Location = new Point(435, 249);
            btn_Cancel.Name = "btn_Cancel";
            btn_Cancel.Size = new Size(76, 22);
            btn_Cancel.StyleController = dataLayoutControl1;
            btn_Cancel.TabIndex = 99;
            btn_Cancel.Text = Resources.Common_Cancel;
            // 
            // btn_Ok
            // 
            btn_Ok.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Ok.Location = new Point(515, 249);
            btn_Ok.Name = "btn_Ok";
            btn_Ok.Size = new Size(77, 22);
            btn_Ok.StyleController = dataLayoutControl1;
            btn_Ok.TabIndex = 100;
            btn_Ok.Text = Resources.Common_Save;
            btn_Ok.Click += btn_Ok_Click;
            // 
            // WarehouseCodeTextEdit
            // 
            WarehouseCodeTextEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "WarehouseCode", true));
            WarehouseCodeTextEdit.Location = new Point(166, 12);
            WarehouseCodeTextEdit.Name = "WarehouseCodeTextEdit";
            WarehouseCodeTextEdit.Size = new Size(133, 20);
            WarehouseCodeTextEdit.StyleController = dataLayoutControl1;
            WarehouseCodeTextEdit.TabIndex = 0;
            // 
            // dcWarehousesBindingSource
            // 
            dcWarehousesBindingSource.DataSource = typeof(Models.DcWarehouse);
            // 
            // WarehouseDescTextEdit
            // 
            WarehouseDescTextEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "WarehouseDesc", true));
            WarehouseDescTextEdit.Location = new Point(166, 60);
            WarehouseDescTextEdit.Name = "WarehouseDescTextEdit";
            WarehouseDescTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            WarehouseDescTextEdit.Size = new Size(133, 20);
            WarehouseDescTextEdit.StyleController = dataLayoutControl1;
            WarehouseDescTextEdit.TabIndex = 3;
            // 
            // WarehouseTypeCodeLookUpEdit
            // 
            WarehouseTypeCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "WarehouseTypeCode", true));
            WarehouseTypeCodeLookUpEdit.Location = new Point(166, 36);
            WarehouseTypeCodeLookUpEdit.Name = "WarehouseTypeCodeLookUpEdit";
            WarehouseTypeCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            WarehouseTypeCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("WarehouseTypeCode", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("WarehouseTypeDesc", "") });
            WarehouseTypeCodeLookUpEdit.Properties.DisplayMember = "WarehouseTypeDesc";
            WarehouseTypeCodeLookUpEdit.Properties.NullText = "";
            WarehouseTypeCodeLookUpEdit.Properties.ValueMember = "WarehouseTypeCode";
            WarehouseTypeCodeLookUpEdit.Size = new Size(133, 20);
            WarehouseTypeCodeLookUpEdit.StyleController = dataLayoutControl1;
            WarehouseTypeCodeLookUpEdit.TabIndex = 2;
            // 
            // OfficeCodeLookUpEdit
            // 
            OfficeCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "OfficeCode", true));
            OfficeCodeLookUpEdit.Location = new Point(457, 36);
            OfficeCodeLookUpEdit.Name = "OfficeCodeLookUpEdit";
            OfficeCodeLookUpEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            OfficeCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            OfficeCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("OfficeCode", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("OfficeDesc", "") });
            OfficeCodeLookUpEdit.Properties.DisplayMember = "OfficeDesc";
            OfficeCodeLookUpEdit.Properties.NullText = "";
            OfficeCodeLookUpEdit.Properties.ValueMember = "OfficeCode";
            OfficeCodeLookUpEdit.Size = new Size(135, 20);
            OfficeCodeLookUpEdit.StyleController = dataLayoutControl1;
            OfficeCodeLookUpEdit.TabIndex = 4;
            // 
            // StoreCodeLookUpEdit
            // 
            StoreCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "StoreCode", true));
            StoreCodeLookUpEdit.Location = new Point(457, 12);
            StoreCodeLookUpEdit.Name = "StoreCodeLookUpEdit";
            StoreCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            StoreCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("StoreCode", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("StoreDesc", "") });
            StoreCodeLookUpEdit.Properties.DisplayMember = "CurrAccDesc";
            StoreCodeLookUpEdit.Properties.NullText = "";
            StoreCodeLookUpEdit.Properties.ValueMember = "CurrAccCode";
            StoreCodeLookUpEdit.Size = new Size(135, 20);
            StoreCodeLookUpEdit.StyleController = dataLayoutControl1;
            StoreCodeLookUpEdit.TabIndex = 1;
            // 
            // PermitNegativeStockCheckEdit
            // 
            PermitNegativeStockCheckEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "PermitNegativeStock", true));
            PermitNegativeStockCheckEdit.Location = new Point(12, 84);
            PermitNegativeStockCheckEdit.Name = "PermitNegativeStockCheckEdit";
            PermitNegativeStockCheckEdit.Properties.Caption = Resources.Entity_Warehouse_PermitNegativeStock;
            PermitNegativeStockCheckEdit.Size = new Size(580, 20);
            PermitNegativeStockCheckEdit.StyleController = dataLayoutControl1;
            PermitNegativeStockCheckEdit.TabIndex = 101;
            // 
            // WarnNegativeStockCheckEdit
            // 
            WarnNegativeStockCheckEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "WarnNegativeStock", true));
            WarnNegativeStockCheckEdit.Location = new Point(12, 108);
            WarnNegativeStockCheckEdit.Name = "WarnNegativeStockCheckEdit";
            WarnNegativeStockCheckEdit.Properties.Caption = Resources.Entity_Warehouse_WarnNegativeStock;
            WarnNegativeStockCheckEdit.Size = new Size(580, 20);
            WarnNegativeStockCheckEdit.StyleController = dataLayoutControl1;
            WarnNegativeStockCheckEdit.TabIndex = 102;
            // 
            // ControlStockLevelCheckEdit
            // 
            ControlStockLevelCheckEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "ControlStockLevel", true));
            ControlStockLevelCheckEdit.Location = new Point(12, 156);
            ControlStockLevelCheckEdit.Name = "ControlStockLevelCheckEdit";
            ControlStockLevelCheckEdit.Properties.Caption = Resources.Entity_Warehouse_ControlStockLevel;
            ControlStockLevelCheckEdit.Size = new Size(580, 20);
            ControlStockLevelCheckEdit.StyleController = dataLayoutControl1;
            ControlStockLevelCheckEdit.TabIndex = 103;
            // 
            // WarnStockLevelRateCheckEdit
            // 
            WarnStockLevelRateCheckEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "WarnStockLevelRate", true));
            WarnStockLevelRateCheckEdit.Location = new Point(12, 132);
            WarnStockLevelRateCheckEdit.Name = "WarnStockLevelRateCheckEdit";
            WarnStockLevelRateCheckEdit.Properties.Caption = Resources.Entity_Warehouse_WarnStockLevelRate;
            WarnStockLevelRateCheckEdit.Size = new Size(580, 20);
            WarnStockLevelRateCheckEdit.StyleController = dataLayoutControl1;
            WarnStockLevelRateCheckEdit.TabIndex = 104;
            // 
            // IsDefaultCheckEdit
            // 
            IsDefaultCheckEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "IsDefault", true));
            IsDefaultCheckEdit.Location = new Point(24, 213);
            IsDefaultCheckEdit.Name = "IsDefaultCheckEdit";
            IsDefaultCheckEdit.Properties.Caption = Resources.Entity_Warehouse_IsDefault;
            IsDefaultCheckEdit.Size = new Size(275, 20);
            IsDefaultCheckEdit.StyleController = dataLayoutControl1;
            IsDefaultCheckEdit.TabIndex = 105;
            // 
            // IsDisabledCheckEdit
            // 
            IsDisabledCheckEdit.DataBindings.Add(new Binding("EditValue", dcWarehousesBindingSource, "IsDisabled", true));
            IsDisabledCheckEdit.Location = new Point(303, 213);
            IsDisabledCheckEdit.Name = "IsDisabledCheckEdit";
            IsDisabledCheckEdit.Properties.Caption = Resources.Common_IsDisabled;
            IsDisabledCheckEdit.Size = new Size(277, 20);
            IsDisabledCheckEdit.StyleController = dataLayoutControl1;
            IsDisabledCheckEdit.TabIndex = 106;
            // 
            // Root
            // 
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            Root.GroupBordersVisible = false;
            Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { autoGeneratedGroup0 });
            Root.Name = "Root";
            Root.Size = new Size(604, 300);
            Root.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            autoGeneratedGroup0.AllowDrawBackground = false;
            autoGeneratedGroup0.GroupBordersVisible = false;
            autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { ItemForWarehouseCode, ItemForStoreCode, ItemForWarehouseTypeCode, ItemForWarehouseDesc, ItemForOfficeCode, layoutControlGroup3, emptySpaceItem1, layoutControlItem2, layoutControlItem1, ItemForPermitNegativeStock, ItemForControlStockLevel, ItemForWarnStockLevelRate, ItemForWarnNegativeStock });
            autoGeneratedGroup0.Location = new Point(0, 0);
            autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            autoGeneratedGroup0.Size = new Size(584, 280);
            // 
            // ItemForWarehouseCode
            // 
            ItemForWarehouseCode.Control = WarehouseCodeTextEdit;
            ItemForWarehouseCode.Location = new Point(0, 0);
            ItemForWarehouseCode.Name = "ItemForWarehouseCode";
            ItemForWarehouseCode.Size = new Size(291, 24);
            ItemForWarehouseCode.TextSize = new Size(142, 13);
            // 
            // ItemForStoreCode
            // 
            ItemForStoreCode.Control = StoreCodeLookUpEdit;
            ItemForStoreCode.Location = new Point(291, 0);
            ItemForStoreCode.Name = "ItemForStoreCode";
            ItemForStoreCode.Size = new Size(293, 24);
            ItemForStoreCode.TextSize = new Size(142, 13);
            // 
            // ItemForWarehouseTypeCode
            // 
            ItemForWarehouseTypeCode.Control = WarehouseTypeCodeLookUpEdit;
            ItemForWarehouseTypeCode.Location = new Point(0, 24);
            ItemForWarehouseTypeCode.Name = "ItemForWarehouseTypeCode";
            ItemForWarehouseTypeCode.Size = new Size(291, 24);
            ItemForWarehouseTypeCode.TextSize = new Size(142, 13);
            // 
            // ItemForWarehouseDesc
            // 
            ItemForWarehouseDesc.Control = WarehouseDescTextEdit;
            ItemForWarehouseDesc.Location = new Point(0, 48);
            ItemForWarehouseDesc.Name = "ItemForWarehouseDesc";
            ItemForWarehouseDesc.Size = new Size(291, 24);
            ItemForWarehouseDesc.TextSize = new Size(142, 13);
            // 
            // ItemForOfficeCode
            // 
            ItemForOfficeCode.Control = OfficeCodeLookUpEdit;
            ItemForOfficeCode.Location = new Point(291, 24);
            ItemForOfficeCode.Name = "ItemForOfficeCode";
            ItemForOfficeCode.Size = new Size(293, 48);
            ItemForOfficeCode.TextSize = new Size(142, 13);
            // 
            // ItemForPermitNegativeStock
            // 
            ItemForPermitNegativeStock.Control = PermitNegativeStockCheckEdit;
            ItemForPermitNegativeStock.Location = new Point(0, 72);
            ItemForPermitNegativeStock.Name = "ItemForPermitNegativeStock";
            ItemForPermitNegativeStock.Size = new Size(584, 24);
            ItemForPermitNegativeStock.TextVisible = false;
            // 
            // ItemForWarnNegativeStock
            // 
            ItemForWarnNegativeStock.Control = WarnNegativeStockCheckEdit;
            ItemForWarnNegativeStock.Location = new Point(0, 96);
            ItemForWarnNegativeStock.Name = "ItemForWarnNegativeStock";
            ItemForWarnNegativeStock.Size = new Size(584, 24);
            ItemForWarnNegativeStock.TextVisible = false;
            // 
            // ItemForControlStockLevel
            // 
            ItemForControlStockLevel.Control = ControlStockLevelCheckEdit;
            ItemForControlStockLevel.Location = new Point(0, 144);
            ItemForControlStockLevel.Name = "ItemForControlStockLevel";
            ItemForControlStockLevel.Size = new Size(584, 24);
            ItemForControlStockLevel.TextVisible = false;
            // 
            // ItemForWarnStockLevelRate
            // 
            ItemForWarnStockLevelRate.Control = WarnStockLevelRateCheckEdit;
            ItemForWarnStockLevelRate.Location = new Point(0, 120);
            ItemForWarnStockLevelRate.Name = "ItemForWarnStockLevelRate";
            ItemForWarnStockLevelRate.Size = new Size(584, 24);
            ItemForWarnStockLevelRate.TextVisible = false;
            // 
            // layoutControlGroup3
            // 
            layoutControlGroup3.GroupStyle = DevExpress.Utils.GroupStyle.Light;
            layoutControlGroup3.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { ItemForIsDefault, ItemForIsDisabled });
            layoutControlGroup3.Location = new Point(0, 168);
            layoutControlGroup3.Name = "layoutControlGroup3";
            layoutControlGroup3.Size = new Size(584, 69);
            layoutControlGroup3.Text = Resources.Form_CurrAcc_Group_Extra;
            // 
            // ItemForIsDefault
            // 
            ItemForIsDefault.Control = IsDefaultCheckEdit;
            ItemForIsDefault.Location = new Point(0, 0);
            ItemForIsDefault.Name = "ItemForIsDefault";
            ItemForIsDefault.Size = new Size(279, 24);
            ItemForIsDefault.TextVisible = false;
            // 
            // ItemForIsDisabled
            // 
            ItemForIsDisabled.Control = IsDisabledCheckEdit;
            ItemForIsDisabled.Location = new Point(279, 0);
            ItemForIsDisabled.Name = "ItemForIsDisabled";
            ItemForIsDisabled.Size = new Size(281, 24);
            ItemForIsDisabled.TextVisible = false;
            // 
            // emptySpaceItem1
            // 
            emptySpaceItem1.Location = new Point(0, 237);
            emptySpaceItem1.Name = "emptySpaceItem1";
            emptySpaceItem1.Size = new Size(423, 43);
            // 
            // layoutControlItem2
            // 
            layoutControlItem2.Control = btn_Cancel;
            layoutControlItem2.Location = new Point(423, 237);
            layoutControlItem2.Name = "layoutControlItem2";
            layoutControlItem2.Size = new Size(80, 43);
            layoutControlItem2.TextVisible = false;
            // 
            // layoutControlItem1
            // 
            layoutControlItem1.Control = btn_Ok;
            layoutControlItem1.Location = new Point(503, 237);
            layoutControlItem1.Name = "layoutControlItem1";
            layoutControlItem1.Size = new Size(81, 43);
            layoutControlItem1.TextVisible = false;
            // 
            // FormWarehouse
            // 
            AutoScaleDimensions = new SizeF(6F, 13F);
            AutoScaleMode = AutoScaleMode.Font;
            AutoValidate = AutoValidate.EnableAllowFocusChange;
            ClientSize = new Size(604, 300);
            Controls.Add(dataLayoutControl1);
            Name = "FormWarehouse";
            Text = Resources.Entity_Warehouse;
            Load += FormWarehouse_Load;
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).EndInit();
            dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)WarehouseCodeTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)dcWarehousesBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)WarehouseDescTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)WarehouseTypeCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)OfficeCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)StoreCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)PermitNegativeStockCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)WarnNegativeStockCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)ControlStockLevelCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)WarnStockLevelRateCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)IsDefaultCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)IsDisabledCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)Root).EndInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarehouseCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForStoreCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarehouseTypeCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarehouseDesc).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForOfficeCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPermitNegativeStock).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarnNegativeStock).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForControlStockLevel).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForWarnStockLevelRate).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlGroup3).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDefault).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDisabled).EndInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private System.Windows.Forms.BindingSource dcWarehousesBindingSource;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;

        private DevExpress.XtraEditors.SimpleButton btn_Cancel;
        private DevExpress.XtraEditors.SimpleButton btn_Ok;

        private DevExpress.XtraEditors.TextEdit WarehouseCodeTextEdit;
        private DevExpress.XtraEditors.TextEdit WarehouseDescTextEdit;

        private DevExpress.XtraEditors.LookUpEdit WarehouseTypeCodeLookUpEdit;
        private DevExpress.XtraEditors.LookUpEdit OfficeCodeLookUpEdit;
        private DevExpress.XtraEditors.LookUpEdit StoreCodeLookUpEdit;

        private DevExpress.XtraEditors.CheckEdit PermitNegativeStockCheckEdit;
        private DevExpress.XtraEditors.CheckEdit WarnNegativeStockCheckEdit;
        private DevExpress.XtraEditors.CheckEdit ControlStockLevelCheckEdit;
        private DevExpress.XtraEditors.CheckEdit WarnStockLevelRateCheckEdit;
        private DevExpress.XtraEditors.CheckEdit IsDefaultCheckEdit;
        private DevExpress.XtraEditors.CheckEdit IsDisabledCheckEdit;

        private DevExpress.XtraLayout.LayoutControlItem ItemForWarehouseCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForWarehouseDesc;
        private DevExpress.XtraLayout.LayoutControlItem ItemForWarehouseTypeCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForOfficeCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForStoreCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForPermitNegativeStock;
        private DevExpress.XtraLayout.LayoutControlItem ItemForWarnNegativeStock;
        private DevExpress.XtraLayout.LayoutControlItem ItemForControlStockLevel;
        private DevExpress.XtraLayout.LayoutControlItem ItemForWarnStockLevelRate;

        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup3;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIsDefault;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIsDisabled;

        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
    }
}
