using Foxoft.Models;
using Foxoft.Properties;

namespace Foxoft
{
    partial class FormPaymentMethod
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            btn_Cancel = new DevExpress.XtraEditors.SimpleButton();
            btn_Ok = new DevExpress.XtraEditors.SimpleButton();
            PaymentMethodIdTextEdit = new DevExpress.XtraEditors.TextEdit();
            dcPaymentMethodsBindingSource = new BindingSource(components);
            PaymentMethodDescTextEdit = new DevExpress.XtraEditors.TextEdit();
            PaymentTypeCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            DefaultCashRegCodeButtonEdit = new DevExpress.XtraEditors.ButtonEdit();
            IsRedirectedCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            RedirectedCurrAccCodeButtonEdit = new DevExpress.XtraEditors.ButtonEdit();
            IsDefaultCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            IsDisabledCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            Root = new DevExpress.XtraLayout.LayoutControlGroup();
            autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            ItemForPaymentMethodId = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForPaymentMethodDesc = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForPaymentTypeCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForDefaultCashRegCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForIsRedirected = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForRedirectedCurrAccCode = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlGroup_Extra = new DevExpress.XtraLayout.LayoutControlGroup();
            ItemForIsDefault = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForIsDisabled = new DevExpress.XtraLayout.LayoutControlItem();
            emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).BeginInit();
            dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)PaymentMethodIdTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dcPaymentMethodsBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)PaymentMethodDescTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)PaymentTypeCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)DefaultCashRegCodeButtonEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)IsRedirectedCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)RedirectedCurrAccCodeButtonEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)IsDefaultCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)IsDisabledCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)Root).BeginInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPaymentMethodId).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPaymentMethodDesc).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPaymentTypeCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDefaultCashRegCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsRedirected).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForRedirectedCurrAccCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlGroup_Extra).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDefault).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDisabled).BeginInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).BeginInit();
            SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            dataLayoutControl1.Controls.Add(btn_Cancel);
            dataLayoutControl1.Controls.Add(btn_Ok);
            dataLayoutControl1.Controls.Add(PaymentMethodIdTextEdit);
            dataLayoutControl1.Controls.Add(PaymentMethodDescTextEdit);
            dataLayoutControl1.Controls.Add(PaymentTypeCodeLookUpEdit);
            dataLayoutControl1.Controls.Add(DefaultCashRegCodeButtonEdit);
            dataLayoutControl1.Controls.Add(IsRedirectedCheckEdit);
            dataLayoutControl1.Controls.Add(RedirectedCurrAccCodeButtonEdit);
            dataLayoutControl1.Controls.Add(IsDefaultCheckEdit);
            dataLayoutControl1.Controls.Add(IsDisabledCheckEdit);
            dataLayoutControl1.DataSource = dcPaymentMethodsBindingSource;
            dataLayoutControl1.Dock = DockStyle.Fill;
            dataLayoutControl1.Location = new Point(0, 0);
            dataLayoutControl1.Name = "dataLayoutControl1";
            dataLayoutControl1.OptionsFocus.MoveFocusRightToLeft = false;
            dataLayoutControl1.Root = Root;
            dataLayoutControl1.Size = new Size(500, 350);
            dataLayoutControl1.TabIndex = 0;
            dataLayoutControl1.Text = "dataLayoutControl1";
            // 
            // btn_Cancel
            // 
            btn_Cancel.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Cancel.Location = new Point(331, 299);
            btn_Cancel.Name = "btn_Cancel";
            btn_Cancel.Size = new Size(76, 22);
            btn_Cancel.StyleController = dataLayoutControl1;
            btn_Cancel.TabIndex = 99;
            btn_Cancel.Text = Resources.Common_Cancel;
            // 
            // btn_Ok
            // 
            btn_Ok.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Ok.Location = new Point(411, 299);
            btn_Ok.Name = "btn_Ok";
            btn_Ok.Size = new Size(77, 22);
            btn_Ok.StyleController = dataLayoutControl1;
            btn_Ok.TabIndex = 100;
            btn_Ok.Text = Resources.Common_Save;
            btn_Ok.Click += btn_Ok_Click;
            // 
            // PaymentMethodIdTextEdit
            // 
            PaymentMethodIdTextEdit.DataBindings.Add(new Binding("EditValue", dcPaymentMethodsBindingSource, "PaymentMethodId", true));
            PaymentMethodIdTextEdit.Location = new Point(166, 12);
            PaymentMethodIdTextEdit.Name = "PaymentMethodIdTextEdit";
            PaymentMethodIdTextEdit.Size = new Size(322, 20);
            PaymentMethodIdTextEdit.StyleController = dataLayoutControl1;
            PaymentMethodIdTextEdit.TabIndex = 0;
            // 
            // dcPaymentMethodsBindingSource
            // 
            dcPaymentMethodsBindingSource.DataSource = typeof(DcPaymentMethod);
            // 
            // PaymentMethodDescTextEdit
            // 
            PaymentMethodDescTextEdit.DataBindings.Add(new Binding("EditValue", dcPaymentMethodsBindingSource, "PaymentMethodDesc", true));
            PaymentMethodDescTextEdit.Location = new Point(166, 36);
            PaymentMethodDescTextEdit.Name = "PaymentMethodDescTextEdit";
            PaymentMethodDescTextEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            PaymentMethodDescTextEdit.Size = new Size(322, 20);
            PaymentMethodDescTextEdit.StyleController = dataLayoutControl1;
            PaymentMethodDescTextEdit.TabIndex = 1;
            // 
            // PaymentTypeCodeLookUpEdit
            // 
            PaymentTypeCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", dcPaymentMethodsBindingSource, "PaymentTypeCode", true));
            PaymentTypeCodeLookUpEdit.Location = new Point(166, 60);
            PaymentTypeCodeLookUpEdit.Name = "PaymentTypeCodeLookUpEdit";
            PaymentTypeCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            PaymentTypeCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("PaymentTypeCode", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("PaymentTypeDesc", "") });
            PaymentTypeCodeLookUpEdit.Properties.DisplayMember = "PaymentTypeDesc";
            PaymentTypeCodeLookUpEdit.Properties.NullText = "";
            PaymentTypeCodeLookUpEdit.Properties.ValueMember = "PaymentTypeCode";
            PaymentTypeCodeLookUpEdit.Size = new Size(322, 20);
            PaymentTypeCodeLookUpEdit.StyleController = dataLayoutControl1;
            PaymentTypeCodeLookUpEdit.TabIndex = 2;
            // 
            // DefaultCashRegCodeButtonEdit
            // 
            DefaultCashRegCodeButtonEdit.DataBindings.Add(new Binding("EditValue", dcPaymentMethodsBindingSource, "DefaultCashRegCode", true));
            DefaultCashRegCodeButtonEdit.Location = new Point(166, 84);
            DefaultCashRegCodeButtonEdit.Name = "DefaultCashRegCodeButtonEdit";
            DefaultCashRegCodeButtonEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton() });
            DefaultCashRegCodeButtonEdit.Size = new Size(322, 20);
            DefaultCashRegCodeButtonEdit.StyleController = dataLayoutControl1;
            DefaultCashRegCodeButtonEdit.TabIndex = 3;
            DefaultCashRegCodeButtonEdit.ButtonPressed += DefaultCashRegCodeButtonEdit_ButtonPressed;
            // 
            // IsRedirectedCheckEdit
            // 
            IsRedirectedCheckEdit.DataBindings.Add(new Binding("EditValue", dcPaymentMethodsBindingSource, "IsRedirected", true));
            IsRedirectedCheckEdit.Location = new Point(12, 108);
            IsRedirectedCheckEdit.Name = "IsRedirectedCheckEdit";
            IsRedirectedCheckEdit.Properties.Caption = Resources.Entity_PaymentMethod_IsRedirected;
            IsRedirectedCheckEdit.Size = new Size(476, 20);
            IsRedirectedCheckEdit.StyleController = dataLayoutControl1;
            IsRedirectedCheckEdit.TabIndex = 4;
            // 
            // RedirectedCurrAccCodeButtonEdit
            // 
            RedirectedCurrAccCodeButtonEdit.DataBindings.Add(new Binding("EditValue", dcPaymentMethodsBindingSource, "RedirectedCurrAccCode", true));
            RedirectedCurrAccCodeButtonEdit.Location = new Point(166, 132);
            RedirectedCurrAccCodeButtonEdit.Name = "RedirectedCurrAccCodeButtonEdit";
            RedirectedCurrAccCodeButtonEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton() });
            RedirectedCurrAccCodeButtonEdit.Size = new Size(322, 20);
            RedirectedCurrAccCodeButtonEdit.StyleController = dataLayoutControl1;
            RedirectedCurrAccCodeButtonEdit.TabIndex = 5;
            RedirectedCurrAccCodeButtonEdit.ButtonPressed += RedirectedCurrAccCodeButtonEdit_ButtonPressed;
            // 
            // IsDefaultCheckEdit
            // 
            IsDefaultCheckEdit.DataBindings.Add(new Binding("EditValue", dcPaymentMethodsBindingSource, "IsDefault", true));
            IsDefaultCheckEdit.Location = new Point(24, 189);
            IsDefaultCheckEdit.Name = "IsDefaultCheckEdit";
            IsDefaultCheckEdit.Properties.Caption = Resources.Entity_PaymentMethod_IsDefault;
            IsDefaultCheckEdit.Size = new Size(226, 20);
            IsDefaultCheckEdit.StyleController = dataLayoutControl1;
            IsDefaultCheckEdit.TabIndex = 6;
            // 
            // IsDisabledCheckEdit
            // 
            IsDisabledCheckEdit.DataBindings.Add(new Binding("EditValue", dcPaymentMethodsBindingSource, "IsDisabled", true));
            IsDisabledCheckEdit.Location = new Point(254, 189);
            IsDisabledCheckEdit.Name = "IsDisabledCheckEdit";
            IsDisabledCheckEdit.Properties.Caption = Resources.Common_IsDisabled;
            IsDisabledCheckEdit.Size = new Size(222, 20);
            IsDisabledCheckEdit.StyleController = dataLayoutControl1;
            IsDisabledCheckEdit.TabIndex = 7;
            // 
            // Root
            // 
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            Root.GroupBordersVisible = false;
            Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { autoGeneratedGroup0 });
            Root.Name = "Root";
            Root.Size = new Size(500, 350);
            Root.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            autoGeneratedGroup0.AllowDrawBackground = false;
            autoGeneratedGroup0.GroupBordersVisible = false;
            autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { ItemForPaymentMethodId, ItemForPaymentMethodDesc, ItemForPaymentTypeCode, ItemForDefaultCashRegCode, ItemForIsRedirected, ItemForRedirectedCurrAccCode, layoutControlGroup_Extra, emptySpaceItem1, layoutControlItem2, layoutControlItem1 });
            autoGeneratedGroup0.Location = new Point(0, 0);
            autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            autoGeneratedGroup0.Size = new Size(480, 330);
            // 
            // ItemForPaymentMethodId
            // 
            ItemForPaymentMethodId.Control = PaymentMethodIdTextEdit;
            ItemForPaymentMethodId.Location = new Point(0, 0);
            ItemForPaymentMethodId.Name = "ItemForPaymentMethodId";
            ItemForPaymentMethodId.Size = new Size(480, 24);
            ItemForPaymentMethodId.TextSize = new Size(142, 13);
            // 
            // ItemForPaymentMethodDesc
            // 
            ItemForPaymentMethodDesc.Control = PaymentMethodDescTextEdit;
            ItemForPaymentMethodDesc.Location = new Point(0, 24);
            ItemForPaymentMethodDesc.Name = "ItemForPaymentMethodDesc";
            ItemForPaymentMethodDesc.Size = new Size(480, 24);
            ItemForPaymentMethodDesc.TextSize = new Size(142, 13);
            // 
            // ItemForPaymentTypeCode
            // 
            ItemForPaymentTypeCode.Control = PaymentTypeCodeLookUpEdit;
            ItemForPaymentTypeCode.Location = new Point(0, 48);
            ItemForPaymentTypeCode.Name = "ItemForPaymentTypeCode";
            ItemForPaymentTypeCode.Size = new Size(480, 24);
            ItemForPaymentTypeCode.TextSize = new Size(142, 13);
            // 
            // ItemForDefaultCashRegCode
            // 
            ItemForDefaultCashRegCode.Control = DefaultCashRegCodeButtonEdit;
            ItemForDefaultCashRegCode.Location = new Point(0, 72);
            ItemForDefaultCashRegCode.Name = "ItemForDefaultCashRegCode";
            ItemForDefaultCashRegCode.Size = new Size(480, 24);
            ItemForDefaultCashRegCode.TextSize = new Size(142, 13);
            // 
            // ItemForIsRedirected
            // 
            ItemForIsRedirected.Control = IsRedirectedCheckEdit;
            ItemForIsRedirected.Location = new Point(0, 96);
            ItemForIsRedirected.Name = "ItemForIsRedirected";
            ItemForIsRedirected.Size = new Size(480, 24);
            ItemForIsRedirected.TextVisible = false;
            // 
            // ItemForRedirectedCurrAccCode
            // 
            ItemForRedirectedCurrAccCode.Control = RedirectedCurrAccCodeButtonEdit;
            ItemForRedirectedCurrAccCode.Location = new Point(0, 120);
            ItemForRedirectedCurrAccCode.Name = "ItemForRedirectedCurrAccCode";
            ItemForRedirectedCurrAccCode.Size = new Size(480, 24);
            ItemForRedirectedCurrAccCode.TextSize = new Size(142, 13);
            // 
            // layoutControlGroup_Extra
            // 
            layoutControlGroup_Extra.GroupStyle = DevExpress.Utils.GroupStyle.Light;
            layoutControlGroup_Extra.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { ItemForIsDefault, ItemForIsDisabled });
            layoutControlGroup_Extra.Location = new Point(0, 144);
            layoutControlGroup_Extra.Name = "layoutControlGroup_Extra";
            layoutControlGroup_Extra.Size = new Size(480, 69);
            layoutControlGroup_Extra.Text = Resources.Form_CurrAcc_Group_Extra;
            // 
            // ItemForIsDefault
            // 
            ItemForIsDefault.Control = IsDefaultCheckEdit;
            ItemForIsDefault.Location = new Point(0, 0);
            ItemForIsDefault.Name = "ItemForIsDefault";
            ItemForIsDefault.Size = new Size(230, 24);
            ItemForIsDefault.TextVisible = false;
            // 
            // ItemForIsDisabled
            // 
            ItemForIsDisabled.Control = IsDisabledCheckEdit;
            ItemForIsDisabled.Location = new Point(230, 0);
            ItemForIsDisabled.Name = "ItemForIsDisabled";
            ItemForIsDisabled.Size = new Size(226, 24);
            ItemForIsDisabled.TextVisible = false;
            // 
            // emptySpaceItem1
            // 
            emptySpaceItem1.Location = new Point(0, 213);
            emptySpaceItem1.Name = "emptySpaceItem1";
            emptySpaceItem1.Size = new Size(319, 117);
            // 
            // layoutControlItem2
            // 
            layoutControlItem2.Control = btn_Cancel;
            layoutControlItem2.Location = new Point(319, 287);
            layoutControlItem2.Name = "layoutControlItem2";
            layoutControlItem2.Size = new Size(80, 43);
            layoutControlItem2.TextVisible = false;
            // 
            // layoutControlItem1
            // 
            layoutControlItem1.Control = btn_Ok;
            layoutControlItem1.Location = new Point(399, 287);
            layoutControlItem1.Name = "layoutControlItem1";
            layoutControlItem1.Size = new Size(81, 43);
            layoutControlItem1.TextVisible = false;
            // 
            // FormPaymentMethod
            // 
            AutoScaleDimensions = new SizeF(6F, 13F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(500, 350);
            Controls.Add(dataLayoutControl1);
            Name = "FormPaymentMethod";
            Text = Resources.Entity_PaymentMethod;
            Load += FormPaymentMethod_Load;
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).EndInit();
            dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)PaymentMethodIdTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)dcPaymentMethodsBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)PaymentMethodDescTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)PaymentTypeCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)DefaultCashRegCodeButtonEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)IsRedirectedCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)RedirectedCurrAccCodeButtonEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)IsDefaultCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)IsDisabledCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)Root).EndInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPaymentMethodId).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPaymentMethodDesc).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPaymentTypeCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDefaultCashRegCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsRedirected).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForRedirectedCurrAccCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlGroup_Extra).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDefault).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDisabled).EndInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private System.Windows.Forms.BindingSource dcPaymentMethodsBindingSource;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;

        private DevExpress.XtraEditors.SimpleButton btn_Cancel;
        private DevExpress.XtraEditors.SimpleButton btn_Ok;

        private DevExpress.XtraEditors.TextEdit PaymentMethodIdTextEdit;
        private DevExpress.XtraEditors.TextEdit PaymentMethodDescTextEdit;

        private DevExpress.XtraEditors.LookUpEdit PaymentTypeCodeLookUpEdit;
        private DevExpress.XtraEditors.ButtonEdit DefaultCashRegCodeButtonEdit;
        private DevExpress.XtraEditors.ButtonEdit RedirectedCurrAccCodeButtonEdit;

        private DevExpress.XtraEditors.CheckEdit IsRedirectedCheckEdit;
        private DevExpress.XtraEditors.CheckEdit IsDefaultCheckEdit;
        private DevExpress.XtraEditors.CheckEdit IsDisabledCheckEdit;

        private DevExpress.XtraLayout.LayoutControlItem ItemForPaymentMethodId;
        private DevExpress.XtraLayout.LayoutControlItem ItemForPaymentMethodDesc;
        private DevExpress.XtraLayout.LayoutControlItem ItemForPaymentTypeCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForDefaultCashRegCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIsRedirected;
        private DevExpress.XtraLayout.LayoutControlItem ItemForRedirectedCurrAccCode;

        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup_Extra;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIsDefault;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIsDisabled;

        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
    }
}
