using DevExpress.XtraEditors.Repository;
using Foxoft.Models;
using Foxoft.Models.Entity;

namespace Foxoft
{
    partial class FormCampaign
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
                components.Dispose();

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            panelHeader = new DevExpress.XtraEditors.PanelControl();
            lblCampaignCode = new DevExpress.XtraEditors.LabelControl();
            lblCampaignDesc = new DevExpress.XtraEditors.LabelControl();
            lblCampaignType = new DevExpress.XtraEditors.LabelControl();
            lblPromoCode = new DevExpress.XtraEditors.LabelControl();
            lblDiscountType = new DevExpress.XtraEditors.LabelControl();
            lblDiscountValue = new DevExpress.XtraEditors.LabelControl();
            lblPriority = new DevExpress.XtraEditors.LabelControl();
            lblStartDate = new DevExpress.XtraEditors.LabelControl();
            lblEndDate = new DevExpress.XtraEditors.LabelControl();
            lblMinInvoiceAmount = new DevExpress.XtraEditors.LabelControl();
            lblMaxDiscountAmount = new DevExpress.XtraEditors.LabelControl();
            lblNote = new DevExpress.XtraEditors.LabelControl();
            CampaignCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            CampaignDescTextEdit = new DevExpress.XtraEditors.TextEdit();
            CampaignTypeCodeComboBoxEdit = new DevExpress.XtraEditors.ComboBoxEdit();
            PromoCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            DiscountTypeCodeComboBoxEdit = new DevExpress.XtraEditors.ComboBoxEdit();
            DiscountValueCalcEdit = new DevExpress.XtraEditors.CalcEdit();
            PrioritySpinEdit = new DevExpress.XtraEditors.SpinEdit();
            IsActiveCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            IsCombinableCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            StartDateDateEdit = new DevExpress.XtraEditors.DateEdit();
            EndDateDateEdit = new DevExpress.XtraEditors.DateEdit();
            MinInvoiceAmountCalcEdit = new DevExpress.XtraEditors.CalcEdit();
            MaxDiscountAmountCalcEdit = new DevExpress.XtraEditors.CalcEdit();
            NoteMemoEdit = new DevExpress.XtraEditors.MemoEdit();
            xtraTabControl1 = new DevExpress.XtraTab.XtraTabControl();
            tabProduct = new DevExpress.XtraTab.XtraTabPage();
            gC_Product = new DevExpress.XtraGrid.GridControl();
            trCampaignProductsBindingSource = new BindingSource(components);
            gV_Product = new DevExpress.XtraGrid.Views.Grid.GridView();
            colCampaignProductId = new DevExpress.XtraGrid.Columns.GridColumn();
            colProductCode = new DevExpress.XtraGrid.Columns.GridColumn();
            repoLUE_ProductCode = new RepositoryItemLookUpEdit();
            panelProduct = new DevExpress.XtraEditors.PanelControl();
            btnDeleteProduct = new DevExpress.XtraEditors.SimpleButton();
            btnAddProduct = new DevExpress.XtraEditors.SimpleButton();
            tabCategory = new DevExpress.XtraTab.XtraTabPage();
            gC_Category = new DevExpress.XtraGrid.GridControl();
            trCampaignCategoriesBindingSource = new BindingSource(components);
            gV_Category = new DevExpress.XtraGrid.Views.Grid.GridView();
            colCampaignCategoryId = new DevExpress.XtraGrid.Columns.GridColumn();
            colHierarchyCode = new DevExpress.XtraGrid.Columns.GridColumn();
            repoLUE_CategoryCode = new RepositoryItemLookUpEdit();
            panelCategory = new DevExpress.XtraEditors.PanelControl();
            btnDeleteCategory = new DevExpress.XtraEditors.SimpleButton();
            btnAddCategory = new DevExpress.XtraEditors.SimpleButton();
            tabCustomer = new DevExpress.XtraTab.XtraTabPage();
            gC_Customer = new DevExpress.XtraGrid.GridControl();
            trCampaignCustomersBindingSource = new BindingSource(components);
            gV_Customer = new DevExpress.XtraGrid.Views.Grid.GridView();
            colCampaignCustomerId = new DevExpress.XtraGrid.Columns.GridColumn();
            colCurrAccCode = new DevExpress.XtraGrid.Columns.GridColumn();
            repoLUE_CustomerCode = new RepositoryItemLookUpEdit();
            panelCustomer = new DevExpress.XtraEditors.PanelControl();
            btnDeleteCustomer = new DevExpress.XtraEditors.SimpleButton();
            btnAddCustomer = new DevExpress.XtraEditors.SimpleButton();
            tabStore = new DevExpress.XtraTab.XtraTabPage();
            gC_Store = new DevExpress.XtraGrid.GridControl();
            trCampaignStoresBindingSource = new BindingSource(components);
            gV_Store = new DevExpress.XtraGrid.Views.Grid.GridView();
            colCampaignStoreId = new DevExpress.XtraGrid.Columns.GridColumn();
            colStoreCode = new DevExpress.XtraGrid.Columns.GridColumn();
            repoLUE_StoreCode = new RepositoryItemLookUpEdit();
            panelStore = new DevExpress.XtraEditors.PanelControl();
            btnDeleteStore = new DevExpress.XtraEditors.SimpleButton();
            btnAddStore = new DevExpress.XtraEditors.SimpleButton();
            tabWarehouse = new DevExpress.XtraTab.XtraTabPage();
            gC_Warehouse = new DevExpress.XtraGrid.GridControl();
            trCampaignWarehousesBindingSource = new BindingSource(components);
            gV_Warehouse = new DevExpress.XtraGrid.Views.Grid.GridView();
            colCampaignWarehouseId = new DevExpress.XtraGrid.Columns.GridColumn();
            colWarehouseCode = new DevExpress.XtraGrid.Columns.GridColumn();
            repoLUE_WarehouseCode = new RepositoryItemLookUpEdit();
            panelWarehouse = new DevExpress.XtraEditors.PanelControl();
            btnDeleteWarehouse = new DevExpress.XtraEditors.SimpleButton();
            btnAddWarehouse = new DevExpress.XtraEditors.SimpleButton();
            tabPaymentMethod = new DevExpress.XtraTab.XtraTabPage();
            gC_PaymentMethod = new DevExpress.XtraGrid.GridControl();
            trCampaignPaymentMethodsBindingSource = new BindingSource(components);
            gV_PaymentMethod = new DevExpress.XtraGrid.Views.Grid.GridView();
            colCampaignPaymentMethodId = new DevExpress.XtraGrid.Columns.GridColumn();
            colPaymentMethodId = new DevExpress.XtraGrid.Columns.GridColumn();
            repoLUE_PaymentMethod = new RepositoryItemLookUpEdit();
            panelPaymentMethod = new DevExpress.XtraEditors.PanelControl();
            btnDeletePaymentMethod = new DevExpress.XtraEditors.SimpleButton();
            btnAddPaymentMethod = new DevExpress.XtraEditors.SimpleButton();
            panelButtons = new DevExpress.XtraEditors.PanelControl();
            btn_Cancel = new DevExpress.XtraEditors.SimpleButton();
            btn_Ok = new DevExpress.XtraEditors.SimpleButton();
            dcCampaignsBindingSource = new BindingSource(components);
            ((System.ComponentModel.ISupportInitialize)panelHeader).BeginInit();
            panelHeader.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)CampaignCodeTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)CampaignDescTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)CampaignTypeCodeComboBoxEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)PromoCodeTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)DiscountTypeCodeComboBoxEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)DiscountValueCalcEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)PrioritySpinEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)IsActiveCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)IsCombinableCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)StartDateDateEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)StartDateDateEdit.Properties.CalendarTimeProperties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)EndDateDateEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)EndDateDateEdit.Properties.CalendarTimeProperties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)MinInvoiceAmountCalcEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)MaxDiscountAmountCalcEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)NoteMemoEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)xtraTabControl1).BeginInit();
            xtraTabControl1.SuspendLayout();
            tabProduct.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)gC_Product).BeginInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignProductsBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gV_Product).BeginInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_ProductCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)panelProduct).BeginInit();
            panelProduct.SuspendLayout();
            tabCategory.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)gC_Category).BeginInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignCategoriesBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gV_Category).BeginInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_CategoryCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)panelCategory).BeginInit();
            panelCategory.SuspendLayout();
            tabCustomer.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)gC_Customer).BeginInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignCustomersBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gV_Customer).BeginInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_CustomerCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)panelCustomer).BeginInit();
            panelCustomer.SuspendLayout();
            tabStore.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)gC_Store).BeginInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignStoresBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gV_Store).BeginInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_StoreCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)panelStore).BeginInit();
            panelStore.SuspendLayout();
            tabWarehouse.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)gC_Warehouse).BeginInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignWarehousesBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gV_Warehouse).BeginInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_WarehouseCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)panelWarehouse).BeginInit();
            panelWarehouse.SuspendLayout();
            tabPaymentMethod.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)gC_PaymentMethod).BeginInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignPaymentMethodsBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gV_PaymentMethod).BeginInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_PaymentMethod).BeginInit();
            ((System.ComponentModel.ISupportInitialize)panelPaymentMethod).BeginInit();
            panelPaymentMethod.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)panelButtons).BeginInit();
            panelButtons.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dcCampaignsBindingSource).BeginInit();
            SuspendLayout();
            // 
            // panelHeader
            // 
            panelHeader.Controls.Add(lblCampaignCode);
            panelHeader.Controls.Add(lblCampaignDesc);
            panelHeader.Controls.Add(lblCampaignType);
            panelHeader.Controls.Add(lblPromoCode);
            panelHeader.Controls.Add(lblDiscountType);
            panelHeader.Controls.Add(lblDiscountValue);
            panelHeader.Controls.Add(lblPriority);
            panelHeader.Controls.Add(lblStartDate);
            panelHeader.Controls.Add(lblEndDate);
            panelHeader.Controls.Add(lblMinInvoiceAmount);
            panelHeader.Controls.Add(lblMaxDiscountAmount);
            panelHeader.Controls.Add(lblNote);
            panelHeader.Controls.Add(CampaignCodeTextEdit);
            panelHeader.Controls.Add(CampaignDescTextEdit);
            panelHeader.Controls.Add(CampaignTypeCodeComboBoxEdit);
            panelHeader.Controls.Add(PromoCodeTextEdit);
            panelHeader.Controls.Add(DiscountTypeCodeComboBoxEdit);
            panelHeader.Controls.Add(DiscountValueCalcEdit);
            panelHeader.Controls.Add(PrioritySpinEdit);
            panelHeader.Controls.Add(IsActiveCheckEdit);
            panelHeader.Controls.Add(IsCombinableCheckEdit);
            panelHeader.Controls.Add(StartDateDateEdit);
            panelHeader.Controls.Add(EndDateDateEdit);
            panelHeader.Controls.Add(MinInvoiceAmountCalcEdit);
            panelHeader.Controls.Add(MaxDiscountAmountCalcEdit);
            panelHeader.Controls.Add(NoteMemoEdit);
            panelHeader.Dock = DockStyle.Top;
            panelHeader.Location = new Point(0, 0);
            panelHeader.Name = "panelHeader";
            panelHeader.Size = new Size(1180, 228);
            // labels
            lblCampaignCode.Location = new Point(12, 15); lblCampaignCode.Text = "Kampaniya kodu";
            lblCampaignDesc.Location = new Point(400, 15); lblCampaignDesc.Text = "Kampaniya adı";
            lblCampaignType.Location = new Point(12, 45); lblCampaignType.Text = "Tip";
            lblPromoCode.Location = new Point(400, 45); lblPromoCode.Text = "Promo code";
            lblDiscountType.Location = new Point(788, 45); lblDiscountType.Text = "Endirim tipi";
            lblDiscountValue.Location = new Point(12, 75); lblDiscountValue.Text = "Endirim";
            lblPriority.Location = new Point(400, 75); lblPriority.Text = "Prioritet";
            lblStartDate.Location = new Point(12, 105); lblStartDate.Text = "Başlama tarixi";
            lblEndDate.Location = new Point(400, 105); lblEndDate.Text = "Bitmə tarixi";
            lblMinInvoiceAmount.Location = new Point(788, 105); lblMinInvoiceAmount.Text = "Min. faktura";
            lblMaxDiscountAmount.Location = new Point(12, 135); lblMaxDiscountAmount.Text = "Maks. endirim";
            lblNote.Location = new Point(12, 165); lblNote.Text = "Qeyd";
            // editors
            CampaignCodeTextEdit.Location = new Point(124, 12); CampaignCodeTextEdit.Size = new Size(240, 20);
            CampaignDescTextEdit.Location = new Point(500, 12); CampaignDescTextEdit.Size = new Size(668, 20);
            CampaignTypeCodeComboBoxEdit.Location = new Point(124, 42); CampaignTypeCodeComboBoxEdit.Size = new Size(240, 20); CampaignTypeCodeComboBoxEdit.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
            PromoCodeTextEdit.Location = new Point(500, 42); PromoCodeTextEdit.Size = new Size(240, 20);
            DiscountTypeCodeComboBoxEdit.Location = new Point(896, 42); DiscountTypeCodeComboBoxEdit.Size = new Size(272, 20); DiscountTypeCodeComboBoxEdit.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
            DiscountValueCalcEdit.Location = new Point(124, 72); DiscountValueCalcEdit.Size = new Size(240, 20); DiscountValueCalcEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            PrioritySpinEdit.Location = new Point(500, 72); PrioritySpinEdit.Size = new Size(240, 20); PrioritySpinEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton() });
            IsActiveCheckEdit.Location = new Point(896, 72); IsActiveCheckEdit.Size = new Size(120, 20); IsActiveCheckEdit.Properties.Caption = "Aktiv";
            IsCombinableCheckEdit.Location = new Point(1024, 72); IsCombinableCheckEdit.Size = new Size(144, 20); IsCombinableCheckEdit.Properties.Caption = "Birləşə bilir";
            StartDateDateEdit.Location = new Point(124, 102); StartDateDateEdit.Size = new Size(240, 20); StartDateDateEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) }); StartDateDateEdit.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            EndDateDateEdit.Location = new Point(500, 102); EndDateDateEdit.Size = new Size(240, 20); EndDateDateEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) }); EndDateDateEdit.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            MinInvoiceAmountCalcEdit.Location = new Point(896, 102); MinInvoiceAmountCalcEdit.Size = new Size(272, 20); MinInvoiceAmountCalcEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            MaxDiscountAmountCalcEdit.Location = new Point(124, 132); MaxDiscountAmountCalcEdit.Size = new Size(240, 20); MaxDiscountAmountCalcEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            NoteMemoEdit.Location = new Point(124, 162); NoteMemoEdit.Size = new Size(1044, 54);
            // 
            // xtraTabControl1
            // 
            xtraTabControl1.Dock = DockStyle.Fill;
            xtraTabControl1.Location = new Point(0, 228);
            xtraTabControl1.Name = "xtraTabControl1";
            xtraTabControl1.SelectedTabPage = tabProduct;
            xtraTabControl1.Size = new Size(1180, 444);
            xtraTabControl1.TabPages.AddRange(new DevExpress.XtraTab.XtraTabPage[] { tabProduct, tabCategory, tabCustomer, tabStore, tabWarehouse, tabPaymentMethod });
            // product
            tabProduct.Controls.Add(gC_Product); tabProduct.Controls.Add(panelProduct); tabProduct.Text = "Məhsullar";
            panelProduct.Controls.Add(btnDeleteProduct); panelProduct.Controls.Add(btnAddProduct); panelProduct.Dock = DockStyle.Top; panelProduct.Size = new Size(1178, 40);
            btnAddProduct.Location = new Point(8, 8); btnAddProduct.Size = new Size(110, 24); btnAddProduct.Text = "Əlavə et"; btnAddProduct.Click += btnAddProduct_Click;
            btnDeleteProduct.Location = new Point(124, 8); btnDeleteProduct.Size = new Size(110, 24); btnDeleteProduct.Text = "Sil"; btnDeleteProduct.Click += btnDeleteProduct_Click;
            gC_Product.DataSource = trCampaignProductsBindingSource; gC_Product.Dock = DockStyle.Fill; gC_Product.Location = new Point(0, 40); gC_Product.MainView = gV_Product; gC_Product.RepositoryItems.AddRange(new RepositoryItem[] { repoLUE_ProductCode }); gC_Product.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { gV_Product });
            gV_Product.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] { colCampaignProductId, colProductCode }); gV_Product.GridControl = gC_Product; gV_Product.OptionsView.ShowGroupPanel = false;
            colCampaignProductId.FieldName = "CampaignProductId"; colProductCode.FieldName = "ProductCode"; colProductCode.Caption = "Məhsul"; colProductCode.ColumnEdit = repoLUE_ProductCode; colProductCode.Visible = true; colProductCode.VisibleIndex = 0;
            repoLUE_ProductCode.AutoHeight = false; repoLUE_ProductCode.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            // category
            tabCategory.Controls.Add(gC_Category); tabCategory.Controls.Add(panelCategory); tabCategory.Text = "Kateqoriyalar";
            panelCategory.Controls.Add(btnDeleteCategory); panelCategory.Controls.Add(btnAddCategory); panelCategory.Dock = DockStyle.Top; panelCategory.Size = new Size(1178, 40);
            btnAddCategory.Location = new Point(8, 8); btnAddCategory.Size = new Size(110, 24); btnAddCategory.Text = "Əlavə et"; btnAddCategory.Click += btnAddCategory_Click;
            btnDeleteCategory.Location = new Point(124, 8); btnDeleteCategory.Size = new Size(110, 24); btnDeleteCategory.Text = "Sil"; btnDeleteCategory.Click += btnDeleteCategory_Click;
            gC_Category.DataSource = trCampaignCategoriesBindingSource; gC_Category.Dock = DockStyle.Fill; gC_Category.Location = new Point(0, 40); gC_Category.MainView = gV_Category; gC_Category.RepositoryItems.AddRange(new RepositoryItem[] { repoLUE_CategoryCode }); gC_Category.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { gV_Category });
            gV_Category.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] { colCampaignCategoryId, colHierarchyCode }); gV_Category.GridControl = gC_Category; gV_Category.OptionsView.ShowGroupPanel = false;
            colCampaignCategoryId.FieldName = "CampaignCategoryId"; colHierarchyCode.FieldName = "HierarchyCode"; colHierarchyCode.Caption = "Kateqoriya"; colHierarchyCode.ColumnEdit = repoLUE_CategoryCode; colHierarchyCode.Visible = true; colHierarchyCode.VisibleIndex = 0;
            repoLUE_CategoryCode.AutoHeight = false; repoLUE_CategoryCode.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            // customer
            tabCustomer.Controls.Add(gC_Customer); tabCustomer.Controls.Add(panelCustomer); tabCustomer.Text = "Müştərilər";
            panelCustomer.Controls.Add(btnDeleteCustomer); panelCustomer.Controls.Add(btnAddCustomer); panelCustomer.Dock = DockStyle.Top; panelCustomer.Size = new Size(1178, 40);
            btnAddCustomer.Location = new Point(8, 8); btnAddCustomer.Size = new Size(110, 24); btnAddCustomer.Text = "Əlavə et"; btnAddCustomer.Click += btnAddCustomer_Click;
            btnDeleteCustomer.Location = new Point(124, 8); btnDeleteCustomer.Size = new Size(110, 24); btnDeleteCustomer.Text = "Sil"; btnDeleteCustomer.Click += btnDeleteCustomer_Click;
            gC_Customer.DataSource = trCampaignCustomersBindingSource; gC_Customer.Dock = DockStyle.Fill; gC_Customer.Location = new Point(0, 40); gC_Customer.MainView = gV_Customer; gC_Customer.RepositoryItems.AddRange(new RepositoryItem[] { repoLUE_CustomerCode }); gC_Customer.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { gV_Customer });
            gV_Customer.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] { colCampaignCustomerId, colCurrAccCode }); gV_Customer.GridControl = gC_Customer; gV_Customer.OptionsView.ShowGroupPanel = false;
            colCampaignCustomerId.FieldName = "CampaignCustomerId"; colCurrAccCode.FieldName = "CurrAccCode"; colCurrAccCode.Caption = "Müştəri"; colCurrAccCode.ColumnEdit = repoLUE_CustomerCode; colCurrAccCode.Visible = true; colCurrAccCode.VisibleIndex = 0;
            repoLUE_CustomerCode.AutoHeight = false; repoLUE_CustomerCode.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            // store
            tabStore.Controls.Add(gC_Store); tabStore.Controls.Add(panelStore); tabStore.Text = "Store";
            panelStore.Controls.Add(btnDeleteStore); panelStore.Controls.Add(btnAddStore); panelStore.Dock = DockStyle.Top; panelStore.Size = new Size(1178, 40);
            btnAddStore.Location = new Point(8, 8); btnAddStore.Size = new Size(110, 24); btnAddStore.Text = "Əlavə et"; btnAddStore.Click += btnAddStore_Click;
            btnDeleteStore.Location = new Point(124, 8); btnDeleteStore.Size = new Size(110, 24); btnDeleteStore.Text = "Sil"; btnDeleteStore.Click += btnDeleteStore_Click;
            gC_Store.DataSource = trCampaignStoresBindingSource; gC_Store.Dock = DockStyle.Fill; gC_Store.Location = new Point(0, 40); gC_Store.MainView = gV_Store; gC_Store.RepositoryItems.AddRange(new RepositoryItem[] { repoLUE_StoreCode }); gC_Store.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { gV_Store });
            gV_Store.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] { colCampaignStoreId, colStoreCode }); gV_Store.GridControl = gC_Store; gV_Store.OptionsView.ShowGroupPanel = false;
            colCampaignStoreId.FieldName = "CampaignStoreId"; colStoreCode.FieldName = "StoreCode"; colStoreCode.Caption = "Store"; colStoreCode.ColumnEdit = repoLUE_StoreCode; colStoreCode.Visible = true; colStoreCode.VisibleIndex = 0;
            repoLUE_StoreCode.AutoHeight = false; repoLUE_StoreCode.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            // warehouse
            tabWarehouse.Controls.Add(gC_Warehouse); tabWarehouse.Controls.Add(panelWarehouse); tabWarehouse.Text = "Depolar";
            panelWarehouse.Controls.Add(btnDeleteWarehouse); panelWarehouse.Controls.Add(btnAddWarehouse); panelWarehouse.Dock = DockStyle.Top; panelWarehouse.Size = new Size(1178, 40);
            btnAddWarehouse.Location = new Point(8, 8); btnAddWarehouse.Size = new Size(110, 24); btnAddWarehouse.Text = "Əlavə et"; btnAddWarehouse.Click += btnAddWarehouse_Click;
            btnDeleteWarehouse.Location = new Point(124, 8); btnDeleteWarehouse.Size = new Size(110, 24); btnDeleteWarehouse.Text = "Sil"; btnDeleteWarehouse.Click += btnDeleteWarehouse_Click;
            gC_Warehouse.DataSource = trCampaignWarehousesBindingSource; gC_Warehouse.Dock = DockStyle.Fill; gC_Warehouse.Location = new Point(0, 40); gC_Warehouse.MainView = gV_Warehouse; gC_Warehouse.RepositoryItems.AddRange(new RepositoryItem[] { repoLUE_WarehouseCode }); gC_Warehouse.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { gV_Warehouse });
            gV_Warehouse.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] { colCampaignWarehouseId, colWarehouseCode }); gV_Warehouse.GridControl = gC_Warehouse; gV_Warehouse.OptionsView.ShowGroupPanel = false;
            colCampaignWarehouseId.FieldName = "CampaignWarehouseId"; colWarehouseCode.FieldName = "WarehouseCode"; colWarehouseCode.Caption = "Depo"; colWarehouseCode.ColumnEdit = repoLUE_WarehouseCode; colWarehouseCode.Visible = true; colWarehouseCode.VisibleIndex = 0;
            repoLUE_WarehouseCode.AutoHeight = false; repoLUE_WarehouseCode.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            // payment method
            tabPaymentMethod.Controls.Add(gC_PaymentMethod); tabPaymentMethod.Controls.Add(panelPaymentMethod); tabPaymentMethod.Text = "Ödəmə üsulları";
            panelPaymentMethod.Controls.Add(btnDeletePaymentMethod); panelPaymentMethod.Controls.Add(btnAddPaymentMethod); panelPaymentMethod.Dock = DockStyle.Top; panelPaymentMethod.Size = new Size(1178, 40);
            btnAddPaymentMethod.Location = new Point(8, 8); btnAddPaymentMethod.Size = new Size(110, 24); btnAddPaymentMethod.Text = "Əlavə et"; btnAddPaymentMethod.Click += btnAddPaymentMethod_Click;
            btnDeletePaymentMethod.Location = new Point(124, 8); btnDeletePaymentMethod.Size = new Size(110, 24); btnDeletePaymentMethod.Text = "Sil"; btnDeletePaymentMethod.Click += btnDeletePaymentMethod_Click;
            gC_PaymentMethod.DataSource = trCampaignPaymentMethodsBindingSource; gC_PaymentMethod.Dock = DockStyle.Fill; gC_PaymentMethod.Location = new Point(0, 40); gC_PaymentMethod.MainView = gV_PaymentMethod; gC_PaymentMethod.RepositoryItems.AddRange(new RepositoryItem[] { repoLUE_PaymentMethod }); gC_PaymentMethod.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { gV_PaymentMethod });
            gV_PaymentMethod.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] { colCampaignPaymentMethodId, colPaymentMethodId }); gV_PaymentMethod.GridControl = gC_PaymentMethod; gV_PaymentMethod.OptionsView.ShowGroupPanel = false;
            colCampaignPaymentMethodId.FieldName = "CampaignPaymentMethodId"; colPaymentMethodId.FieldName = "PaymentMethodId"; colPaymentMethodId.Caption = "Ödəmə üsulu"; colPaymentMethodId.ColumnEdit = repoLUE_PaymentMethod; colPaymentMethodId.Visible = true; colPaymentMethodId.VisibleIndex = 0;
            repoLUE_PaymentMethod.AutoHeight = false; repoLUE_PaymentMethod.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            // panelButtons
            panelButtons.Controls.Add(btn_Cancel); 
            panelButtons.Controls.Add(btn_Ok); 
            panelButtons.Dock = DockStyle.Bottom; 
            panelButtons.Location = new Point(0, 672); 
            panelButtons.Size = new Size(1180, 48);
            btn_Ok.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btn_Ok.Location = new Point(942, 10); 
            btn_Ok.Size = new Size(110, 28); 
            btn_Ok.Text = "Yadda saxla"; 
            btn_Ok.Click += btn_Ok_Click;
            btn_Cancel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btn_Cancel.Location = new Point(1058, 10); 
            btn_Cancel.Size = new Size(110, 28); 
            btn_Cancel.Text = "Bağla"; 
            btn_Cancel.Click += btn_Cancel_Click;
            // binding sources
            dcCampaignsBindingSource.DataSource = typeof(DcCampaign);
            trCampaignProductsBindingSource.DataSource = typeof(TrCampaignProduct); trCampaignProductsBindingSource.AddingNew += trCampaignProductsBindingSource_AddingNew;
            trCampaignCategoriesBindingSource.DataSource = typeof(TrCampaignCategory); trCampaignCategoriesBindingSource.AddingNew += trCampaignCategoriesBindingSource_AddingNew;
            trCampaignCustomersBindingSource.DataSource = typeof(TrCampaignCustomer); trCampaignCustomersBindingSource.AddingNew += trCampaignCustomersBindingSource_AddingNew;
            trCampaignStoresBindingSource.DataSource = typeof(TrCampaignStore); trCampaignStoresBindingSource.AddingNew += trCampaignStoresBindingSource_AddingNew;
            trCampaignWarehousesBindingSource.DataSource = typeof(TrCampaignWarehouse); trCampaignWarehousesBindingSource.AddingNew += trCampaignWarehousesBindingSource_AddingNew;
            trCampaignPaymentMethodsBindingSource.DataSource = typeof(TrCampaignPaymentMethod); trCampaignPaymentMethodsBindingSource.AddingNew += trCampaignPaymentMethodsBindingSource_AddingNew;
            // form
            AutoScaleDimensions = new SizeF(6F, 13F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1180, 720);
            Controls.Add(xtraTabControl1);
            Controls.Add(panelButtons);
            Controls.Add(panelHeader);
            Name = "FormCampaign";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Kampaniya";
            Load += FormCampaign_Load;
            ((System.ComponentModel.ISupportInitialize)panelHeader).EndInit();
            panelHeader.ResumeLayout(false);
            panelHeader.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)CampaignCodeTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)CampaignDescTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)CampaignTypeCodeComboBoxEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)PromoCodeTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)DiscountTypeCodeComboBoxEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)DiscountValueCalcEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)PrioritySpinEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)IsActiveCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)IsCombinableCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)StartDateDateEdit.Properties.CalendarTimeProperties).EndInit();
            ((System.ComponentModel.ISupportInitialize)StartDateDateEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)EndDateDateEdit.Properties.CalendarTimeProperties).EndInit();
            ((System.ComponentModel.ISupportInitialize)EndDateDateEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)MinInvoiceAmountCalcEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)MaxDiscountAmountCalcEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)NoteMemoEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)xtraTabControl1).EndInit();
            xtraTabControl1.ResumeLayout(false);
            tabProduct.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)gC_Product).EndInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignProductsBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)gV_Product).EndInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_ProductCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)panelProduct).EndInit();
            panelProduct.ResumeLayout(false);
            tabCategory.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)gC_Category).EndInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignCategoriesBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)gV_Category).EndInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_CategoryCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)panelCategory).EndInit();
            panelCategory.ResumeLayout(false);
            tabCustomer.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)gC_Customer).EndInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignCustomersBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)gV_Customer).EndInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_CustomerCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)panelCustomer).EndInit();
            panelCustomer.ResumeLayout(false);
            tabStore.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)gC_Store).EndInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignStoresBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)gV_Store).EndInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_StoreCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)panelStore).EndInit();
            panelStore.ResumeLayout(false);
            tabWarehouse.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)gC_Warehouse).EndInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignWarehousesBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)gV_Warehouse).EndInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_WarehouseCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)panelWarehouse).EndInit();
            panelWarehouse.ResumeLayout(false);
            tabPaymentMethod.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)gC_PaymentMethod).EndInit();
            ((System.ComponentModel.ISupportInitialize)trCampaignPaymentMethodsBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)gV_PaymentMethod).EndInit();
            ((System.ComponentModel.ISupportInitialize)repoLUE_PaymentMethod).EndInit();
            ((System.ComponentModel.ISupportInitialize)panelPaymentMethod).EndInit();
            panelPaymentMethod.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)panelButtons).EndInit();
            panelButtons.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dcCampaignsBindingSource).EndInit();
            ResumeLayout(false);
        }

        private DevExpress.XtraEditors.PanelControl panelHeader;
        private DevExpress.XtraEditors.LabelControl lblCampaignCode;
        private DevExpress.XtraEditors.LabelControl lblCampaignDesc;
        private DevExpress.XtraEditors.LabelControl lblCampaignType;
        private DevExpress.XtraEditors.LabelControl lblPromoCode;
        private DevExpress.XtraEditors.LabelControl lblDiscountType;
        private DevExpress.XtraEditors.LabelControl lblDiscountValue;
        private DevExpress.XtraEditors.LabelControl lblPriority;
        private DevExpress.XtraEditors.LabelControl lblStartDate;
        private DevExpress.XtraEditors.LabelControl lblEndDate;
        private DevExpress.XtraEditors.LabelControl lblMinInvoiceAmount;
        private DevExpress.XtraEditors.LabelControl lblMaxDiscountAmount;
        private DevExpress.XtraEditors.LabelControl lblNote;
        private DevExpress.XtraEditors.TextEdit CampaignCodeTextEdit;
        private DevExpress.XtraEditors.TextEdit CampaignDescTextEdit;
        private DevExpress.XtraEditors.ComboBoxEdit CampaignTypeCodeComboBoxEdit;
        private DevExpress.XtraEditors.TextEdit PromoCodeTextEdit;
        private DevExpress.XtraEditors.ComboBoxEdit DiscountTypeCodeComboBoxEdit;
        private DevExpress.XtraEditors.CalcEdit DiscountValueCalcEdit;
        private DevExpress.XtraEditors.SpinEdit PrioritySpinEdit;
        private DevExpress.XtraEditors.CheckEdit IsActiveCheckEdit;
        private DevExpress.XtraEditors.CheckEdit IsCombinableCheckEdit;
        private DevExpress.XtraEditors.DateEdit StartDateDateEdit;
        private DevExpress.XtraEditors.DateEdit EndDateDateEdit;
        private DevExpress.XtraEditors.CalcEdit MinInvoiceAmountCalcEdit;
        private DevExpress.XtraEditors.CalcEdit MaxDiscountAmountCalcEdit;
        private DevExpress.XtraEditors.MemoEdit NoteMemoEdit;
        private DevExpress.XtraTab.XtraTabControl xtraTabControl1;
        private DevExpress.XtraTab.XtraTabPage tabProduct;
        private DevExpress.XtraTab.XtraTabPage tabCategory;
        private DevExpress.XtraTab.XtraTabPage tabCustomer;
        private DevExpress.XtraTab.XtraTabPage tabStore;
        private DevExpress.XtraTab.XtraTabPage tabWarehouse;
        private DevExpress.XtraTab.XtraTabPage tabPaymentMethod;
        private DevExpress.XtraGrid.GridControl gC_Product;
        private DevExpress.XtraGrid.Views.Grid.GridView gV_Product;
        private DevExpress.XtraGrid.GridControl gC_Category;
        private DevExpress.XtraGrid.Views.Grid.GridView gV_Category;
        private DevExpress.XtraGrid.GridControl gC_Customer;
        private DevExpress.XtraGrid.Views.Grid.GridView gV_Customer;
        private DevExpress.XtraGrid.GridControl gC_Store;
        private DevExpress.XtraGrid.Views.Grid.GridView gV_Store;
        private DevExpress.XtraGrid.GridControl gC_Warehouse;
        private DevExpress.XtraGrid.Views.Grid.GridView gV_Warehouse;
        private DevExpress.XtraGrid.GridControl gC_PaymentMethod;
        private DevExpress.XtraGrid.Views.Grid.GridView gV_PaymentMethod;
        private BindingSource dcCampaignsBindingSource;
        private BindingSource trCampaignProductsBindingSource;
        private BindingSource trCampaignCategoriesBindingSource;
        private BindingSource trCampaignCustomersBindingSource;
        private BindingSource trCampaignStoresBindingSource;
        private BindingSource trCampaignWarehousesBindingSource;
        private BindingSource trCampaignPaymentMethodsBindingSource;
        private RepositoryItemLookUpEdit repoLUE_ProductCode;
        private RepositoryItemLookUpEdit repoLUE_CategoryCode;
        private RepositoryItemLookUpEdit repoLUE_CustomerCode;
        private RepositoryItemLookUpEdit repoLUE_StoreCode;
        private RepositoryItemLookUpEdit repoLUE_WarehouseCode;
        private RepositoryItemLookUpEdit repoLUE_PaymentMethod;
        private DevExpress.XtraEditors.PanelControl panelButtons;
        private DevExpress.XtraEditors.SimpleButton btn_Ok;
        private DevExpress.XtraEditors.SimpleButton btn_Cancel;
        private DevExpress.XtraEditors.PanelControl panelProduct;
        private DevExpress.XtraEditors.PanelControl panelCategory;
        private DevExpress.XtraEditors.PanelControl panelCustomer;
        private DevExpress.XtraEditors.PanelControl panelStore;
        private DevExpress.XtraEditors.PanelControl panelWarehouse;
        private DevExpress.XtraEditors.PanelControl panelPaymentMethod;
        private DevExpress.XtraEditors.SimpleButton btnAddProduct;
        private DevExpress.XtraEditors.SimpleButton btnDeleteProduct;
        private DevExpress.XtraEditors.SimpleButton btnAddCategory;
        private DevExpress.XtraEditors.SimpleButton btnDeleteCategory;
        private DevExpress.XtraEditors.SimpleButton btnAddCustomer;
        private DevExpress.XtraEditors.SimpleButton btnDeleteCustomer;
        private DevExpress.XtraEditors.SimpleButton btnAddStore;
        private DevExpress.XtraEditors.SimpleButton btnDeleteStore;
        private DevExpress.XtraEditors.SimpleButton btnAddWarehouse;
        private DevExpress.XtraEditors.SimpleButton btnDeleteWarehouse;
        private DevExpress.XtraEditors.SimpleButton btnAddPaymentMethod;
        private DevExpress.XtraEditors.SimpleButton btnDeletePaymentMethod;
        private DevExpress.XtraGrid.Columns.GridColumn colCampaignProductId;
        private DevExpress.XtraGrid.Columns.GridColumn colProductCode;
        private DevExpress.XtraGrid.Columns.GridColumn colCampaignCategoryId;
        private DevExpress.XtraGrid.Columns.GridColumn colHierarchyCode;
        private DevExpress.XtraGrid.Columns.GridColumn colCampaignCustomerId;
        private DevExpress.XtraGrid.Columns.GridColumn colCurrAccCode;
        private DevExpress.XtraGrid.Columns.GridColumn colCampaignStoreId;
        private DevExpress.XtraGrid.Columns.GridColumn colStoreCode;
        private DevExpress.XtraGrid.Columns.GridColumn colCampaignWarehouseId;
        private DevExpress.XtraGrid.Columns.GridColumn colWarehouseCode;
        private DevExpress.XtraGrid.Columns.GridColumn colCampaignPaymentMethodId;
        private DevExpress.XtraGrid.Columns.GridColumn colPaymentMethodId;
    }
}