
namespace Foxoft
{
    partial class FormStore
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            btn_Cancel = new DevExpress.XtraEditors.SimpleButton();
            btn_Ok = new DevExpress.XtraEditors.SimpleButton();
            CurrAccCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            dcCurrAccsBindingSource = new BindingSource(components);
            IsDisabledCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            CurrAccTypeCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            CurrAccDescTextEdit = new DevExpress.XtraEditors.TextEdit();
            OfficeCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            StoreCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            Root = new DevExpress.XtraLayout.LayoutControlGroup();
            autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            ItemForCurrAccCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForCurrAccTypeCode = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            ItemForCurrAccDesc = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForOfficeCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForStoreCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForIsDisabled = new DevExpress.XtraLayout.LayoutControlItem();
            bindingSource1 = new BindingSource(components);
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).BeginInit();
            dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)CurrAccCodeTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dcCurrAccsBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)IsDisabledCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)CurrAccTypeCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)CurrAccDescTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)OfficeCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)StoreCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)Root).BeginInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccTypeCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccDesc).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForOfficeCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForStoreCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDisabled).BeginInit();
            ((System.ComponentModel.ISupportInitialize)bindingSource1).BeginInit();
            SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            dataLayoutControl1.Controls.Add(btn_Cancel);
            dataLayoutControl1.Controls.Add(btn_Ok);
            dataLayoutControl1.Controls.Add(CurrAccCodeTextEdit);
            dataLayoutControl1.Controls.Add(IsDisabledCheckEdit);
            dataLayoutControl1.Controls.Add(CurrAccTypeCodeLookUpEdit);
            dataLayoutControl1.Controls.Add(CurrAccDescTextEdit);
            dataLayoutControl1.Controls.Add(OfficeCodeLookUpEdit);
            dataLayoutControl1.Controls.Add(StoreCodeLookUpEdit);
            dataLayoutControl1.DataSource = dcCurrAccsBindingSource;
            dataLayoutControl1.Dock = DockStyle.Fill;
            dataLayoutControl1.Location = new Point(0, 0);
            dataLayoutControl1.Name = "dataLayoutControl1";
            dataLayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new Rectangle(1023, 140, 650, 400);
            dataLayoutControl1.OptionsFocus.MoveFocusRightToLeft = false;
            dataLayoutControl1.Root = Root;
            dataLayoutControl1.Size = new Size(600, 156);
            dataLayoutControl1.TabIndex = 0;
            dataLayoutControl1.Text = "dataLayoutControl1";
            dataLayoutControl1.FieldRetrieving += dataLayoutControl1_FieldRetrieving;
            // 
            // btn_Cancel
            // 
            btn_Cancel.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Cancel.Location = new Point(436, 84);
            btn_Cancel.Name = "btn_Cancel";
            btn_Cancel.Size = new Size(74, 60);
            btn_Cancel.StyleController = dataLayoutControl1;
            btn_Cancel.TabIndex = 19;
            btn_Cancel.Text = "simpleButton2";
            // 
            // btn_Ok
            // 
            btn_Ok.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Ok.Location = new Point(514, 84);
            btn_Ok.Name = "btn_Ok";
            btn_Ok.Size = new Size(74, 60);
            btn_Ok.StyleController = dataLayoutControl1;
            btn_Ok.TabIndex = 20;
            btn_Ok.Text = "simpleButton1";
            btn_Ok.Click += btn_Ok_Click;
            // 
            // CurrAccCodeTextEdit
            // 
            CurrAccCodeTextEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "CurrAccCode", true));
            CurrAccCodeTextEdit.Location = new Point(122, 12);
            CurrAccCodeTextEdit.Name = "CurrAccCodeTextEdit";
            CurrAccCodeTextEdit.Size = new Size(175, 20);
            CurrAccCodeTextEdit.StyleController = dataLayoutControl1;
            CurrAccCodeTextEdit.TabIndex = 0;
            // 
            // dcCurrAccsBindingSource
            // 
            dcCurrAccsBindingSource.DataSource = typeof(Models.DcCurrAcc);
            dcCurrAccsBindingSource.AddingNew += dcCurrAccsBindingSource_AddingNew;
            // 
            // IsDisabledCheckEdit
            // 
            IsDisabledCheckEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "IsDisabled", true));
            IsDisabledCheckEdit.Location = new Point(301, 60);
            IsDisabledCheckEdit.Name = "IsDisabledCheckEdit";
            IsDisabledCheckEdit.Properties.Caption = "Qeyri-Aktiv";
            IsDisabledCheckEdit.Properties.GlyphAlignment = DevExpress.Utils.HorzAlignment.Default;
            IsDisabledCheckEdit.Size = new Size(287, 20);
            IsDisabledCheckEdit.StyleController = dataLayoutControl1;
            IsDisabledCheckEdit.TabIndex = 17;
            // 
            // CurrAccTypeCodeLookUpEdit
            // 
            CurrAccTypeCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "CurrAccTypeCode", true));
            CurrAccTypeCodeLookUpEdit.Location = new Point(122, 36);
            CurrAccTypeCodeLookUpEdit.Name = "CurrAccTypeCodeLookUpEdit";
            CurrAccTypeCodeLookUpEdit.Properties.Appearance.Options.UseTextOptions = true;
            CurrAccTypeCodeLookUpEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            CurrAccTypeCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            CurrAccTypeCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("CurrAccTypeCode", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("CurrAccTypeDesc", "") });
            CurrAccTypeCodeLookUpEdit.Properties.DisplayMember = "CurrAccTypeDesc";
            CurrAccTypeCodeLookUpEdit.Properties.NullText = "";
            CurrAccTypeCodeLookUpEdit.Properties.ValueMember = "CurrAccTypeCode";
            CurrAccTypeCodeLookUpEdit.Size = new Size(175, 20);
            CurrAccTypeCodeLookUpEdit.StyleController = dataLayoutControl1;
            CurrAccTypeCodeLookUpEdit.TabIndex = 3;
            // 
            // CurrAccDescTextEdit
            // 
            CurrAccDescTextEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "CurrAccDesc", true));
            CurrAccDescTextEdit.Location = new Point(122, 60);
            CurrAccDescTextEdit.Name = "CurrAccDescTextEdit";
            CurrAccDescTextEdit.Size = new Size(175, 20);
            CurrAccDescTextEdit.StyleController = dataLayoutControl1;
            CurrAccDescTextEdit.TabIndex = 5;
            // 
            // OfficeCodeLookUpEdit
            // 
            OfficeCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "OfficeCode", true));
            OfficeCodeLookUpEdit.Location = new Point(411, 36);
            OfficeCodeLookUpEdit.Name = "OfficeCodeLookUpEdit";
            OfficeCodeLookUpEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            OfficeCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            OfficeCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("OfficeCode", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("OfficeDesc", "") });
            OfficeCodeLookUpEdit.Properties.DisplayMember = "OfficeDesc";
            OfficeCodeLookUpEdit.Properties.NullText = "";
            OfficeCodeLookUpEdit.Properties.ValueMember = "OfficeCode";
            OfficeCodeLookUpEdit.Size = new Size(177, 20);
            OfficeCodeLookUpEdit.StyleController = dataLayoutControl1;
            OfficeCodeLookUpEdit.TabIndex = 6;
            // 
            // StoreCodeLookUpEdit
            // 
            StoreCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "StoreCode", true));
            StoreCodeLookUpEdit.Location = new Point(411, 12);
            StoreCodeLookUpEdit.Name = "StoreCodeLookUpEdit";
            StoreCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            StoreCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("CurrAccCode", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("CurrAccDesc", "") });
            StoreCodeLookUpEdit.Properties.DisplayMember = "CurrAccDesc";
            StoreCodeLookUpEdit.Properties.NullText = "";
            StoreCodeLookUpEdit.Properties.ValueMember = "CurrAccCode";
            StoreCodeLookUpEdit.Size = new Size(177, 20);
            StoreCodeLookUpEdit.StyleController = dataLayoutControl1;
            StoreCodeLookUpEdit.TabIndex = 2;
            // 
            // Root
            // 
            Root.CustomizationFormText = "Root";
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            Root.GroupBordersVisible = false;
            Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { autoGeneratedGroup0 });
            Root.Name = "Root";
            Root.Size = new Size(600, 156);
            Root.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            autoGeneratedGroup0.AllowDrawBackground = false;
            autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
            autoGeneratedGroup0.GroupBordersVisible = false;
            autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { ItemForCurrAccCode, ItemForCurrAccTypeCode, layoutControlItem1, layoutControlItem2, emptySpaceItem1, ItemForCurrAccDesc, ItemForOfficeCode, ItemForStoreCode, ItemForIsDisabled });
            autoGeneratedGroup0.Location = new Point(0, 0);
            autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            autoGeneratedGroup0.Size = new Size(580, 136);
            // 
            // ItemForCurrAccCode
            // 
            ItemForCurrAccCode.Control = CurrAccCodeTextEdit;
            ItemForCurrAccCode.ControlAlignment = ContentAlignment.TopLeft;
            ItemForCurrAccCode.CustomizationFormText = "Cari Hesab Kodu";
            ItemForCurrAccCode.Location = new Point(0, 0);
            ItemForCurrAccCode.Name = "ItemForCurrAccCode";
            ItemForCurrAccCode.Size = new Size(289, 24);
            ItemForCurrAccCode.Text = "Cari Hesab Kodu";
            ItemForCurrAccCode.TextSize = new Size(98, 13);
            // 
            // ItemForCurrAccTypeCode
            // 
            ItemForCurrAccTypeCode.Control = CurrAccTypeCodeLookUpEdit;
            ItemForCurrAccTypeCode.ControlAlignment = ContentAlignment.TopLeft;
            ItemForCurrAccTypeCode.CustomizationFormText = "Cari Hesab Tipi Kodu";
            ItemForCurrAccTypeCode.Location = new Point(0, 24);
            ItemForCurrAccTypeCode.Name = "ItemForCurrAccTypeCode";
            ItemForCurrAccTypeCode.Size = new Size(289, 24);
            ItemForCurrAccTypeCode.Text = "Cari Hesab Tipi Kodu";
            ItemForCurrAccTypeCode.TextSize = new Size(98, 13);
            // 
            // layoutControlItem1
            // 
            layoutControlItem1.Control = btn_Ok;
            layoutControlItem1.ControlAlignment = ContentAlignment.TopLeft;
            layoutControlItem1.CustomizationFormText = "layoutControlItem1";
            layoutControlItem1.Location = new Point(502, 72);
            layoutControlItem1.MinSize = new Size(78, 26);
            layoutControlItem1.Name = "layoutControlItem1";
            layoutControlItem1.Size = new Size(78, 64);
            layoutControlItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            layoutControlItem1.TextSize = new Size(0, 0);
            layoutControlItem1.TextVisible = false;
            // 
            // layoutControlItem2
            // 
            layoutControlItem2.Control = btn_Cancel;
            layoutControlItem2.ControlAlignment = ContentAlignment.TopLeft;
            layoutControlItem2.CustomizationFormText = "layoutControlItem2";
            layoutControlItem2.Location = new Point(424, 72);
            layoutControlItem2.MinSize = new Size(78, 26);
            layoutControlItem2.Name = "layoutControlItem2";
            layoutControlItem2.Size = new Size(78, 64);
            layoutControlItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            layoutControlItem2.TextSize = new Size(0, 0);
            layoutControlItem2.TextVisible = false;
            // 
            // emptySpaceItem1
            // 
            emptySpaceItem1.AllowHotTrack = false;
            emptySpaceItem1.CustomizationFormText = "emptySpaceItem1";
            emptySpaceItem1.Location = new Point(0, 72);
            emptySpaceItem1.Name = "emptySpaceItem1";
            emptySpaceItem1.Size = new Size(424, 64);
            emptySpaceItem1.TextSize = new Size(0, 0);
            // 
            // ItemForCurrAccDesc
            // 
            ItemForCurrAccDesc.Control = CurrAccDescTextEdit;
            ItemForCurrAccDesc.Location = new Point(0, 48);
            ItemForCurrAccDesc.Name = "ItemForCurrAccDesc";
            ItemForCurrAccDesc.Size = new Size(289, 24);
            ItemForCurrAccDesc.Text = "Cari Hesab Adı";
            ItemForCurrAccDesc.TextSize = new Size(98, 13);
            // 
            // ItemForOfficeCode
            // 
            ItemForOfficeCode.Control = OfficeCodeLookUpEdit;
            ItemForOfficeCode.Location = new Point(289, 24);
            ItemForOfficeCode.Name = "ItemForOfficeCode";
            ItemForOfficeCode.Size = new Size(291, 24);
            ItemForOfficeCode.Text = "Ofis";
            ItemForOfficeCode.TextSize = new Size(98, 13);
            // 
            // ItemForStoreCode
            // 
            ItemForStoreCode.Control = StoreCodeLookUpEdit;
            ItemForStoreCode.Location = new Point(289, 0);
            ItemForStoreCode.Name = "ItemForStoreCode";
            ItemForStoreCode.Size = new Size(291, 24);
            ItemForStoreCode.Text = "Mağaza";
            ItemForStoreCode.TextSize = new Size(98, 13);
            // 
            // ItemForIsDisabled
            // 
            ItemForIsDisabled.Control = IsDisabledCheckEdit;
            ItemForIsDisabled.ControlAlignment = ContentAlignment.TopLeft;
            ItemForIsDisabled.CustomizationFormText = "Qeyri-Aktiv";
            ItemForIsDisabled.Location = new Point(289, 48);
            ItemForIsDisabled.Name = "ItemForIsDisabled";
            ItemForIsDisabled.Size = new Size(291, 24);
            ItemForIsDisabled.Text = "Qeyri-Aktiv";
            ItemForIsDisabled.TextSize = new Size(0, 0);
            ItemForIsDisabled.TextVisible = false;
            // 
            // bindingSource1
            // 
            bindingSource1.DataSource = typeof(Models.DcCurrAcc);
            // 
            // FormStore
            // 
            AutoScaleDimensions = new SizeF(6F, 13F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(600, 156);
            Controls.Add(dataLayoutControl1);
            Name = "FormStore";
            Text = "Cari Hesab";
            Load += FormFormStore_Load;
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).EndInit();
            dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)CurrAccCodeTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)dcCurrAccsBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)IsDisabledCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)CurrAccTypeCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)CurrAccDescTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)OfficeCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)StoreCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)Root).EndInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccTypeCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).EndInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccDesc).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForOfficeCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForStoreCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDisabled).EndInit();
            ((System.ComponentModel.ISupportInitialize)bindingSource1).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private System.Windows.Forms.BindingSource dcCurrAccsBindingSource;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraEditors.SimpleButton btn_Cancel;
        private DevExpress.XtraEditors.SimpleButton btn_Ok;
        private DevExpress.XtraEditors.TextEdit CurrAccCodeTextEdit;
        private DevExpress.XtraEditors.CheckEdit IsDisabledCheckEdit;
        private DevExpress.XtraEditors.TextEdit BonusCardNumTextEdit;
        private DevExpress.XtraEditors.TextEdit AddressTextEdit;
        private DevExpress.XtraEditors.TextEdit PhoneNumTextEdit;
        private DevExpress.XtraEditors.DateEdit BirthDateDateEdit;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCurrAccCode;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup3;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIsDisabled;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup2;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCurrAccTypeCode;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
        private DevExpress.XtraEditors.LookUpEdit CurrAccTypeCodeLookUpEdit;
        private DevExpress.XtraEditors.TextEdit CurrAccDescTextEdit;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCurrAccDesc;
        private DevExpress.XtraLayout.LayoutControlItem ItemForOfficeCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForStoreCode;
        private DevExpress.XtraEditors.LookUpEdit OfficeCodeLookUpEdit;
        private DevExpress.XtraEditors.LookUpEdit StoreCodeLookUpEdit;
        private System.Windows.Forms.BindingSource bindingSource1;
    }
}