using Foxoft.Properties;

namespace Foxoft
{
    partial class FormStore
    {
        private System.ComponentModel.IContainer components = null;
        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private DevExpress.XtraEditors.SimpleButton btn_Cancel;
        private DevExpress.XtraEditors.SimpleButton btn_Ok;
        private DevExpress.XtraEditors.TextEdit CurrAccCodeTextEdit;
        private System.Windows.Forms.BindingSource dcCurrAccsBindingSource;
        private DevExpress.XtraEditors.CheckEdit IsDisabledCheckEdit;
        private DevExpress.XtraEditors.LookUpEdit CurrAccTypeCodeLookUpEdit;
        private DevExpress.XtraEditors.TextEdit CurrAccDescTextEdit;
        private DevExpress.XtraEditors.LookUpEdit OfficeCodeLookUpEdit;
        private DevExpress.XtraEditors.TextEdit DesignFileFolderTextEdit;
        private DevExpress.XtraEditors.CheckEdit SalesmanContinuityCheckEdit;
        private DevExpress.XtraEditors.TextEdit ImageFolderTextEdit;
        private DevExpress.XtraEditors.TextEdit PrinterNameTextEdit;
        private DevExpress.XtraEditors.LookUpEdit DefaultUnitOfMeasureIdLookUpEdit;
        private DevExpress.XtraEditors.TextEdit PhoneNumTextEdit;
        private DevExpress.XtraEditors.TextEdit textEdit2;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCurrAccCode;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
        private DevExpress.XtraLayout.LayoutControlItem ItemForOfficeCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCurrAccDesc;
        private DevExpress.XtraLayout.LayoutControlItem ItemForSalesmanContinuity;
        private DevExpress.XtraLayout.LayoutControlItem ItemForPrinterName;
        private DevExpress.XtraLayout.LayoutControlItem ItemForDesignFileFolder;
        private DevExpress.XtraLayout.LayoutControlItem ItemForImageFolder;
        private DevExpress.XtraLayout.LayoutControlItem ItemForDefaultUnitOfMeasureId;
        private DevExpress.XtraLayout.LayoutControlItem ItemForIsDisabled;
        private DevExpress.XtraLayout.LayoutControlItem ItemForCurrAccTypeCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForAddress;
        private DevExpress.XtraLayout.LayoutControlItem ItemForPhoneNum;
        private System.Windows.Forms.BindingSource bindingSource1;
        private DevExpress.XtraEditors.DXErrorProvider.DXErrorProvider dxErrorProvider1;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormStore));
            dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            btn_Cancel = new DevExpress.XtraEditors.SimpleButton();
            btn_Ok = new DevExpress.XtraEditors.SimpleButton();
            CurrAccCodeTextEdit = new DevExpress.XtraEditors.TextEdit();
            dcCurrAccsBindingSource = new BindingSource(components);
            IsDisabledCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            CurrAccTypeCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            CurrAccDescTextEdit = new DevExpress.XtraEditors.TextEdit();
            OfficeCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            DesignFileFolderTextEdit = new DevExpress.XtraEditors.TextEdit();
            SalesmanContinuityCheckEdit = new DevExpress.XtraEditors.CheckEdit();
            ImageFolderTextEdit = new DevExpress.XtraEditors.TextEdit();
            PrinterNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            DefaultUnitOfMeasureIdLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            PhoneNumTextEdit = new DevExpress.XtraEditors.TextEdit();
            textEdit2 = new DevExpress.XtraEditors.TextEdit();
            Root = new DevExpress.XtraLayout.LayoutControlGroup();
            autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            ItemForCurrAccCode = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            ItemForOfficeCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForCurrAccDesc = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForSalesmanContinuity = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForPrinterName = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForDesignFileFolder = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForImageFolder = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForDefaultUnitOfMeasureId = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForIsDisabled = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForCurrAccTypeCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForAddress = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForPhoneNum = new DevExpress.XtraLayout.LayoutControlItem();
            bindingSource1 = new BindingSource(components);
            dxErrorProvider1 = new DevExpress.XtraEditors.DXErrorProvider.DXErrorProvider(components);
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).BeginInit();
            dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)CurrAccCodeTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dcCurrAccsBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)IsDisabledCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)CurrAccTypeCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)CurrAccDescTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)OfficeCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)DesignFileFolderTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)SalesmanContinuityCheckEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ImageFolderTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)PrinterNameTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)DefaultUnitOfMeasureIdLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)PhoneNumTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)textEdit2.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)Root).BeginInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForOfficeCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccDesc).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForSalesmanContinuity).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPrinterName).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDesignFileFolder).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForImageFolder).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDefaultUnitOfMeasureId).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDisabled).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccTypeCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForAddress).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPhoneNum).BeginInit();
            ((System.ComponentModel.ISupportInitialize)bindingSource1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dxErrorProvider1).BeginInit();
            SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            dataLayoutControl1.Controls.Add(btn_Cancel);
            dataLayoutControl1.Controls.Add(btn_Ok);
            dataLayoutControl1.Controls.Add(CurrAccCodeTextEdit);
            dataLayoutControl1.Controls.Add(IsDisabledCheckEdit);
            dataLayoutControl1.Controls.Add(CurrAccTypeCodeLookUpEdit);
            dataLayoutControl1.Controls.Add(CurrAccDescTextEdit);
            dataLayoutControl1.Controls.Add(OfficeCodeLookUpEdit);
            dataLayoutControl1.Controls.Add(DesignFileFolderTextEdit);
            dataLayoutControl1.Controls.Add(SalesmanContinuityCheckEdit);
            dataLayoutControl1.Controls.Add(ImageFolderTextEdit);
            dataLayoutControl1.Controls.Add(PrinterNameTextEdit);
            dataLayoutControl1.Controls.Add(DefaultUnitOfMeasureIdLookUpEdit);
            dataLayoutControl1.Controls.Add(PhoneNumTextEdit);
            dataLayoutControl1.Controls.Add(textEdit2);
            dataLayoutControl1.DataSource = dcCurrAccsBindingSource;
            dataLayoutControl1.Dock = DockStyle.Fill;
            dataLayoutControl1.Location = new Point(0, 0);
            dataLayoutControl1.Name = "dataLayoutControl1";
            dataLayoutControl1.OptionsCustomizationForm.DesignTimeCustomizationFormPositionAndSize = new Rectangle(1023, 140, 650, 400);
            dataLayoutControl1.OptionsFocus.MoveFocusRightToLeft = false;
            dataLayoutControl1.Root = Root;
            dataLayoutControl1.Size = new Size(543, 238);
            dataLayoutControl1.TabIndex = 0;
            dataLayoutControl1.Text = "dataLayoutControl1";
            dataLayoutControl1.FieldRetrieving += dataLayoutControl1_FieldRetrieving;
            // 
            // btn_Cancel
            // 
            btn_Cancel.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Cancel.ImageOptions.SvgImage = (DevExpress.Utils.Svg.SvgImage)resources.GetObject("btn_Cancel.ImageOptions.SvgImage");
            btn_Cancel.Location = new Point(379, 180);
            btn_Cancel.Name = "btn_Cancel";
            btn_Cancel.Size = new Size(74, 46);
            btn_Cancel.StyleController = dataLayoutControl1;
            btn_Cancel.TabIndex = 19;
            btn_Cancel.Text = "simpleButton2";
            // 
            // btn_Ok
            // 
            btn_Ok.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Ok.ImageOptions.SvgImage = (DevExpress.Utils.Svg.SvgImage)resources.GetObject("btn_Ok.ImageOptions.SvgImage");
            btn_Ok.Location = new Point(457, 180);
            btn_Ok.Name = "btn_Ok";
            btn_Ok.Size = new Size(74, 46);
            btn_Ok.StyleController = dataLayoutControl1;
            btn_Ok.TabIndex = 20;
            btn_Ok.Text = "simpleButton1";
            btn_Ok.Click += btn_Ok_Click;
            // 
            // CurrAccCodeTextEdit
            // 
            CurrAccCodeTextEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "CurrAccCode", true));
            CurrAccCodeTextEdit.Location = new Point(122, 12);
            CurrAccCodeTextEdit.Name = "CurrAccCodeTextEdit";
            CurrAccCodeTextEdit.Size = new Size(147, 20);
            CurrAccCodeTextEdit.StyleController = dataLayoutControl1;
            CurrAccCodeTextEdit.TabIndex = 0;
            // 
            // dcCurrAccsBindingSource
            // 
            dcCurrAccsBindingSource.DataSource = typeof(Models.DcCurrAcc);
            dcCurrAccsBindingSource.AddingNew += dcCurrAccsBindingSource_AddingNew;
            // 
            // IsDisabledCheckEdit
            // 
            IsDisabledCheckEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "IsDisabled", true));
            IsDisabledCheckEdit.Location = new Point(273, 156);
            IsDisabledCheckEdit.Name = "IsDisabledCheckEdit";
            IsDisabledCheckEdit.Properties.Caption = Resources.Form_Store_Save;
            IsDisabledCheckEdit.Properties.GlyphAlignment = DevExpress.Utils.HorzAlignment.Default;
            IsDisabledCheckEdit.Size = new Size(258, 20);
            IsDisabledCheckEdit.StyleController = dataLayoutControl1;
            IsDisabledCheckEdit.TabIndex = 17;
            // 
            // CurrAccTypeCodeLookUpEdit
            // 
            CurrAccTypeCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "CurrAccTypeCode", true));
            CurrAccTypeCodeLookUpEdit.Location = new Point(383, 12);
            CurrAccTypeCodeLookUpEdit.Name = "CurrAccTypeCodeLookUpEdit";
            CurrAccTypeCodeLookUpEdit.Properties.Appearance.Options.UseTextOptions = true;
            CurrAccTypeCodeLookUpEdit.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
            CurrAccTypeCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            CurrAccTypeCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("CurrAccTypeCode", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("CurrAccTypeDesc", "") });
            CurrAccTypeCodeLookUpEdit.Properties.DisplayMember = "CurrAccTypeDesc";
            CurrAccTypeCodeLookUpEdit.Properties.NullText = "";
            CurrAccTypeCodeLookUpEdit.Properties.ValueMember = "CurrAccTypeCode";
            CurrAccTypeCodeLookUpEdit.Size = new Size(148, 20);
            CurrAccTypeCodeLookUpEdit.StyleController = dataLayoutControl1;
            CurrAccTypeCodeLookUpEdit.TabIndex = 3;
            // 
            // CurrAccDescTextEdit
            // 
            CurrAccDescTextEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "CurrAccDesc", true));
            CurrAccDescTextEdit.Location = new Point(122, 36);
            CurrAccDescTextEdit.Name = "CurrAccDescTextEdit";
            CurrAccDescTextEdit.Size = new Size(147, 20);
            CurrAccDescTextEdit.StyleController = dataLayoutControl1;
            CurrAccDescTextEdit.TabIndex = 5;
            // 
            // OfficeCodeLookUpEdit
            // 
            OfficeCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "OfficeCode", true));
            OfficeCodeLookUpEdit.Location = new Point(383, 36);
            OfficeCodeLookUpEdit.Name = "OfficeCodeLookUpEdit";
            OfficeCodeLookUpEdit.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.False;
            OfficeCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            OfficeCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("OfficeCode", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("OfficeDesc", "") });
            OfficeCodeLookUpEdit.Properties.DisplayMember = "OfficeDesc";
            OfficeCodeLookUpEdit.Properties.NullText = "";
            OfficeCodeLookUpEdit.Properties.ValueMember = "OfficeCode";
            OfficeCodeLookUpEdit.Size = new Size(148, 20);
            OfficeCodeLookUpEdit.StyleController = dataLayoutControl1;
            OfficeCodeLookUpEdit.TabIndex = 6;
            // 
            // DesignFileFolderTextEdit
            // 
            DesignFileFolderTextEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "SettingStore.DesignFileFolder", true));
            DesignFileFolderTextEdit.Location = new Point(122, 108);
            DesignFileFolderTextEdit.Name = "DesignFileFolderTextEdit";
            DesignFileFolderTextEdit.Size = new Size(409, 20);
            DesignFileFolderTextEdit.StyleController = dataLayoutControl1;
            DesignFileFolderTextEdit.TabIndex = 21;
            // 
            // SalesmanContinuityCheckEdit
            // 
            SalesmanContinuityCheckEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "SettingStore.SalesmanContinuity", true));
            SalesmanContinuityCheckEdit.Location = new Point(12, 156);
            SalesmanContinuityCheckEdit.Name = "SalesmanContinuityCheckEdit";
            SalesmanContinuityCheckEdit.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Default;
            SalesmanContinuityCheckEdit.Properties.Caption = Resources.Form_Store_Cancel;
            SalesmanContinuityCheckEdit.Size = new Size(257, 20);
            SalesmanContinuityCheckEdit.StyleController = dataLayoutControl1;
            SalesmanContinuityCheckEdit.TabIndex = 22;
            // 
            // ImageFolderTextEdit
            // 
            ImageFolderTextEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "SettingStore.ImageFolder", true));
            ImageFolderTextEdit.Location = new Point(122, 132);
            ImageFolderTextEdit.Name = "ImageFolderTextEdit";
            ImageFolderTextEdit.Size = new Size(409, 20);
            ImageFolderTextEdit.StyleController = dataLayoutControl1;
            ImageFolderTextEdit.TabIndex = 23;
            // 
            // PrinterNameTextEdit
            // 
            PrinterNameTextEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "SettingStore.PrinterName", true));
            PrinterNameTextEdit.Location = new Point(122, 60);
            PrinterNameTextEdit.Name = "PrinterNameTextEdit";
            PrinterNameTextEdit.Size = new Size(147, 20);
            PrinterNameTextEdit.StyleController = dataLayoutControl1;
            PrinterNameTextEdit.TabIndex = 24;
            // 
            // DefaultUnitOfMeasureIdLookUpEdit
            // 
            DefaultUnitOfMeasureIdLookUpEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "SettingStore.DefaultUnitOfMeasureId", true));
            DefaultUnitOfMeasureIdLookUpEdit.Location = new Point(383, 60);
            DefaultUnitOfMeasureIdLookUpEdit.Name = "DefaultUnitOfMeasureIdLookUpEdit";
            DefaultUnitOfMeasureIdLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            DefaultUnitOfMeasureIdLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("UnitOfMeasureId", ""), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("UnitOfMeasureDesc", "") });
            DefaultUnitOfMeasureIdLookUpEdit.Properties.DisplayMember = "UnitOfMeasureDesc";
            DefaultUnitOfMeasureIdLookUpEdit.Properties.NullText = "";
            DefaultUnitOfMeasureIdLookUpEdit.Properties.ValueMember = "UnitOfMeasureId";
            DefaultUnitOfMeasureIdLookUpEdit.Size = new Size(148, 20);
            DefaultUnitOfMeasureIdLookUpEdit.StyleController = dataLayoutControl1;
            DefaultUnitOfMeasureIdLookUpEdit.TabIndex = 25;
            // 
            // PhoneNumTextEdit
            // 
            PhoneNumTextEdit.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "PhoneNum", true));
            PhoneNumTextEdit.EditValue = "+994";
            PhoneNumTextEdit.Location = new Point(122, 84);
            PhoneNumTextEdit.Name = "PhoneNumTextEdit";
            PhoneNumTextEdit.Properties.MaskSettings.Set("MaskManagerType", typeof(DevExpress.Data.Mask.RegExpMaskManager));
            PhoneNumTextEdit.Properties.MaskSettings.Set("allowBlankInput", true);
            PhoneNumTextEdit.Properties.MaskSettings.Set("mask", "\\+?[1-9]\\d{0,2}([ ]?\\d{2,4}){2,6}");
            PhoneNumTextEdit.Properties.MaskSettings.Set("showPlaceholders", false);
            PhoneNumTextEdit.Size = new Size(147, 20);
            PhoneNumTextEdit.StyleController = dataLayoutControl1;
            PhoneNumTextEdit.TabIndex = 13;
            PhoneNumTextEdit.Validating += PhoneNumTextEdit_Validating;
            // 
            // textEdit2
            // 
            textEdit2.DataBindings.Add(new Binding("EditValue", dcCurrAccsBindingSource, "Address", true));
            textEdit2.Location = new Point(383, 84);
            textEdit2.Name = "textEdit2";
            textEdit2.Size = new Size(148, 20);
            textEdit2.StyleController = dataLayoutControl1;
            textEdit2.TabIndex = 27;
            // 
            // Root
            // 
            Root.CustomizationFormText = "Root";
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            Root.GroupBordersVisible = false;
            Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { autoGeneratedGroup0 });
            Root.Name = "Root";
            Root.Size = new Size(543, 238);
            Root.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            autoGeneratedGroup0.AllowDrawBackground = false;
            autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
            autoGeneratedGroup0.GroupBordersVisible = false;
            autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { ItemForCurrAccCode, layoutControlItem1, layoutControlItem2, emptySpaceItem1, ItemForOfficeCode, ItemForCurrAccDesc, ItemForSalesmanContinuity, ItemForPrinterName, ItemForDesignFileFolder, ItemForImageFolder, ItemForDefaultUnitOfMeasureId, ItemForIsDisabled, ItemForCurrAccTypeCode, ItemForAddress, ItemForPhoneNum });
            autoGeneratedGroup0.Location = new Point(0, 0);
            autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            autoGeneratedGroup0.Size = new Size(523, 218);
            // 
            // ItemForCurrAccCode
            // 
            ItemForCurrAccCode.Control = CurrAccCodeTextEdit;
            ItemForCurrAccCode.ControlAlignment = ContentAlignment.TopLeft;
            ItemForCurrAccCode.CustomizationFormText = "Cari Hesab Kodu";
            ItemForCurrAccCode.Location = new Point(0, 0);
            ItemForCurrAccCode.Name = "ItemForCurrAccCode";
            ItemForCurrAccCode.Size = new Size(261, 24);
            ItemForCurrAccCode.Text = Resources.Form_Store_AccountCode;
            ItemForCurrAccCode.TextSize = new Size(98, 13);
            // 
            // layoutControlItem1
            // 
            layoutControlItem1.Control = btn_Ok;
            layoutControlItem1.ControlAlignment = ContentAlignment.TopLeft;
            layoutControlItem1.CustomizationFormText = "layoutControlItem1";
            layoutControlItem1.Location = new Point(445, 168);
            layoutControlItem1.MinSize = new Size(78, 26);
            layoutControlItem1.Name = "layoutControlItem1";
            layoutControlItem1.Size = new Size(78, 50);
            layoutControlItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            layoutControlItem1.TextVisible = false;
            // 
            // layoutControlItem2
            // 
            layoutControlItem2.Control = btn_Cancel;
            layoutControlItem2.ControlAlignment = ContentAlignment.TopLeft;
            layoutControlItem2.CustomizationFormText = "layoutControlItem2";
            layoutControlItem2.Location = new Point(367, 168);
            layoutControlItem2.MinSize = new Size(78, 26);
            layoutControlItem2.Name = "layoutControlItem2";
            layoutControlItem2.Size = new Size(78, 50);
            layoutControlItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            layoutControlItem2.TextVisible = false;
            // 
            // emptySpaceItem1
            // 
            emptySpaceItem1.CustomizationFormText = "emptySpaceItem1";
            emptySpaceItem1.Location = new Point(0, 168);
            emptySpaceItem1.Name = "emptySpaceItem1";
            emptySpaceItem1.Size = new Size(367, 50);
            // 
            // ItemForOfficeCode
            // 
            ItemForOfficeCode.Control = OfficeCodeLookUpEdit;
            ItemForOfficeCode.Location = new Point(261, 24);
            ItemForOfficeCode.Name = "ItemForOfficeCode";
            ItemForOfficeCode.Size = new Size(262, 24);
            ItemForOfficeCode.Text = Resources.Form_Store_OfficeCode;
            ItemForOfficeCode.TextSize = new Size(98, 13);
            // 
            // ItemForCurrAccDesc
            // 
            ItemForCurrAccDesc.Control = CurrAccDescTextEdit;
            ItemForCurrAccDesc.Location = new Point(0, 24);
            ItemForCurrAccDesc.Name = "ItemForCurrAccDesc";
            ItemForCurrAccDesc.Size = new Size(261, 24);
            ItemForCurrAccDesc.Text = Resources.Form_Store_Save;
            ItemForCurrAccDesc.TextSize = new Size(98, 13);
            // 
            // ItemForSalesmanContinuity
            // 
            ItemForSalesmanContinuity.Control = SalesmanContinuityCheckEdit;
            ItemForSalesmanContinuity.Location = new Point(0, 144);
            ItemForSalesmanContinuity.Name = "Mağaza Parametr";
            ItemForSalesmanContinuity.Size = new Size(261, 24);
            ItemForSalesmanContinuity.TextVisible = false;
            // 
            // ItemForPrinterName
            // 
            ItemForPrinterName.Control = PrinterNameTextEdit;
            ItemForPrinterName.Location = new Point(0, 48);
            ItemForPrinterName.Name = "item1";
            ItemForPrinterName.Size = new Size(261, 24);
            ItemForPrinterName.Text = Resources.Form_Store_PrinterName;
            ItemForPrinterName.TextSize = new Size(98, 13);
            // 
            // ItemForDesignFileFolder
            // 
            ItemForDesignFileFolder.Control = DesignFileFolderTextEdit;
            ItemForDesignFileFolder.Location = new Point(0, 96);
            ItemForDesignFileFolder.Name = "ItemForSettingStore";
            ItemForDesignFileFolder.Size = new Size(523, 24);
            ItemForDesignFileFolder.Text = Resources.Form_Store_DesignFileFolder;
            ItemForDesignFileFolder.TextSize = new Size(98, 13);
            // 
            // ItemForImageFolder
            // 
            ItemForImageFolder.Control = ImageFolderTextEdit;
            ItemForImageFolder.Location = new Point(0, 120);
            ItemForImageFolder.Name = "item0";
            ItemForImageFolder.Size = new Size(523, 24);
            ItemForImageFolder.Text = Resources.Form_Store_ImageFolder;
            ItemForImageFolder.TextSize = new Size(98, 13);
            // 
            // ItemForDefaultUnitOfMeasureId
            // 
            ItemForDefaultUnitOfMeasureId.Control = DefaultUnitOfMeasureIdLookUpEdit;
            ItemForDefaultUnitOfMeasureId.Location = new Point(261, 48);
            ItemForDefaultUnitOfMeasureId.Name = "item2";
            ItemForDefaultUnitOfMeasureId.Size = new Size(262, 24);
            ItemForDefaultUnitOfMeasureId.Text = Resources.Form_Store_DefaultUnitOfMeasure;
            ItemForDefaultUnitOfMeasureId.TextSize = new Size(98, 13);
            // 
            // ItemForIsDisabled
            // 
            ItemForIsDisabled.Control = IsDisabledCheckEdit;
            ItemForIsDisabled.ControlAlignment = ContentAlignment.TopLeft;
            ItemForIsDisabled.CustomizationFormText = "Qeyri-Aktiv";
            ItemForIsDisabled.Location = new Point(261, 144);
            ItemForIsDisabled.Name = "ItemForIsDisabled";
            ItemForIsDisabled.Size = new Size(262, 24);
            ItemForIsDisabled.Text = "Qeyri-Aktiv";
            ItemForIsDisabled.TextVisible = false;
            // 
            // ItemForCurrAccTypeCode
            // 
            ItemForCurrAccTypeCode.Control = CurrAccTypeCodeLookUpEdit;
            ItemForCurrAccTypeCode.ControlAlignment = ContentAlignment.TopLeft;
            ItemForCurrAccTypeCode.CustomizationFormText = "Cari Hesab Tipi Kodu";
            ItemForCurrAccTypeCode.Location = new Point(261, 0);
            ItemForCurrAccTypeCode.Name = "ItemForCurrAccTypeCode";
            ItemForCurrAccTypeCode.Size = new Size(262, 24);
            ItemForCurrAccTypeCode.Text = Resources.Form_Store_AccountCode;
            ItemForCurrAccTypeCode.TextSize = new Size(98, 13);
            // 
            // ItemForAddress
            // 
            ItemForAddress.Control = textEdit2;
            ItemForAddress.Location = new Point(261, 72);
            ItemForAddress.Name = "ItemForAddress";
            ItemForAddress.Size = new Size(262, 24);
            ItemForAddress.TextSize = new Size(98, 13);
            // 
            // ItemForPhoneNum
            // 
            ItemForPhoneNum.Control = PhoneNumTextEdit;
            ItemForPhoneNum.Location = new Point(0, 72);
            ItemForPhoneNum.Name = "ItemForPhoneNum";
            ItemForPhoneNum.Size = new Size(261, 24);
            ItemForPhoneNum.TextSize = new Size(98, 13);
            // 
            // bindingSource1
            // 
            bindingSource1.DataSource = typeof(Models.DcCurrAcc);
            // 
            // dxErrorProvider1
            // 
            dxErrorProvider1.ContainerControl = this;
            // 
            // FormStore
            // 
            AutoScaleDimensions = new SizeF(6F, 13F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(543, 238);
            Controls.Add(dataLayoutControl1);
            Name = "FormStore";
            Text = Resources.Form_Store_Caption;
            Load += FormFormStore_Load;
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).EndInit();
            dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)CurrAccCodeTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)dcCurrAccsBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)IsDisabledCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)CurrAccTypeCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)CurrAccDescTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)OfficeCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)DesignFileFolderTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)SalesmanContinuityCheckEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)ImageFolderTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)PrinterNameTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)DefaultUnitOfMeasureIdLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)PhoneNumTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)textEdit2.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)Root).EndInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).EndInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForOfficeCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccDesc).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForSalesmanContinuity).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPrinterName).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDesignFileFolder).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForImageFolder).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDefaultUnitOfMeasureId).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForIsDisabled).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForCurrAccTypeCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForAddress).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForPhoneNum).EndInit();
            ((System.ComponentModel.ISupportInitialize)bindingSource1).EndInit();
            ((System.ComponentModel.ISupportInitialize)dxErrorProvider1).EndInit();
            ResumeLayout(false);
        }
    }
}
