// <auto-generated />
using Foxoft.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Foxoft.Migrations
{
    [DbContext(typeof(subContext))]
    [Migration("20341225122211_AddInstallmentPlanSeedData")]
    partial class AddInstallmentPlanSeedData
    {
    }
}
