using Foxoft.Models;
using Foxoft.Models.Entity;
using Foxoft.Properties;
using System;
using System.ComponentModel;
using System.Windows.Forms;

namespace Foxoft
{
    partial class FormDocumentLock
    {
        private IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            btn_Cancel = new DevExpress.XtraEditors.SimpleButton();
            btn_Ok = new DevExpress.XtraEditors.SimpleButton();

            LockIdTextEdit = new DevExpress.XtraEditors.TextEdit();
            DocumentTypeTextEdit = new DevExpress.XtraEditors.TextEdit();
            DocumentIdTextEdit = new DevExpress.XtraEditors.TextEdit();
            LockedByUserIdTextEdit = new DevExpress.XtraEditors.TextEdit();
            LockedByUserNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            LockedAtUtcDateEdit = new DevExpress.XtraEditors.DateEdit();
            LastHeartbeatAtUtcDateEdit = new DevExpress.XtraEditors.DateEdit();
            MachineNameTextEdit = new DevExpress.XtraEditors.TextEdit();
            AppInstanceIdTextEdit = new DevExpress.XtraEditors.TextEdit();
            ReasonMemoEdit = new DevExpress.XtraEditors.MemoEdit();

            documentLocksBindingSource = new BindingSource(components);

            Root = new DevExpress.XtraLayout.LayoutControlGroup();
            autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();

            ItemForLockId = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForDocumentType = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForDocumentId = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForLockedByUserId = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForLockedByUserName = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForLockedAtUtc = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForLastHeartbeatAtUtc = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForMachineName = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForAppInstanceId = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForReason = new DevExpress.XtraLayout.LayoutControlItem();

            emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();

            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).BeginInit();
            dataLayoutControl1.SuspendLayout();

            ((System.ComponentModel.ISupportInitialize)LockIdTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)DocumentTypeTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)DocumentIdTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)LockedByUserIdTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)LockedByUserNameTextEdit.Properties).BeginInit();

            ((System.ComponentModel.ISupportInitialize)LockedAtUtcDateEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)LockedAtUtcDateEdit.Properties.CalendarTimeProperties).BeginInit();

            ((System.ComponentModel.ISupportInitialize)LastHeartbeatAtUtcDateEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)LastHeartbeatAtUtcDateEdit.Properties.CalendarTimeProperties).BeginInit();

            ((System.ComponentModel.ISupportInitialize)MachineNameTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)AppInstanceIdTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ReasonMemoEdit.Properties).BeginInit();

            ((System.ComponentModel.ISupportInitialize)documentLocksBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)Root).BeginInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).BeginInit();

            ((System.ComponentModel.ISupportInitialize)ItemForLockId).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDocumentType).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDocumentId).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForLockedByUserId).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForLockedByUserName).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForLockedAtUtc).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForLastHeartbeatAtUtc).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForMachineName).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForAppInstanceId).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForReason).BeginInit();

            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).BeginInit();

            SuspendLayout();

            // documentLocksBindingSource
            documentLocksBindingSource.DataSource = typeof(DocumentLock);

            // dataLayoutControl1
            dataLayoutControl1.DataSource = documentLocksBindingSource;
            dataLayoutControl1.Dock = DockStyle.Fill;
            dataLayoutControl1.Controls.Add(btn_Cancel);
            dataLayoutControl1.Controls.Add(btn_Ok);

            dataLayoutControl1.Controls.Add(LockIdTextEdit);
            dataLayoutControl1.Controls.Add(DocumentTypeTextEdit);
            dataLayoutControl1.Controls.Add(DocumentIdTextEdit);
            dataLayoutControl1.Controls.Add(LockedByUserIdTextEdit);
            dataLayoutControl1.Controls.Add(LockedByUserNameTextEdit);
            dataLayoutControl1.Controls.Add(LockedAtUtcDateEdit);
            dataLayoutControl1.Controls.Add(LastHeartbeatAtUtcDateEdit);
            dataLayoutControl1.Controls.Add(MachineNameTextEdit);
            dataLayoutControl1.Controls.Add(AppInstanceIdTextEdit);
            dataLayoutControl1.Controls.Add(ReasonMemoEdit);

            dataLayoutControl1.Location = new System.Drawing.Point(0, 0);
            dataLayoutControl1.Name = "dataLayoutControl1";
            dataLayoutControl1.OptionsFocus.MoveFocusRightToLeft = false;
            dataLayoutControl1.Root = Root;
            dataLayoutControl1.Size = new System.Drawing.Size(640, 360);
            dataLayoutControl1.TabIndex = 0;
            dataLayoutControl1.Text = "dataLayoutControl1";
            dataLayoutControl1.FieldRetrieving += dataLayoutControl1_FieldRetrieving;

            // btn_Cancel
            btn_Cancel.Location = new System.Drawing.Point(471, 326);
            btn_Cancel.Name = "btn_Cancel";
            btn_Cancel.Size = new System.Drawing.Size(76, 22);
            btn_Cancel.StyleController = dataLayoutControl1;
            btn_Cancel.TabIndex = 99;
            btn_Cancel.Text = Resources.Common_Cancel;

            // btn_Ok
            btn_Ok.Location = new System.Drawing.Point(551, 326);
            btn_Ok.Name = "btn_Ok";
            btn_Ok.Size = new System.Drawing.Size(77, 22);
            btn_Ok.StyleController = dataLayoutControl1;
            btn_Ok.TabIndex = 100;
            btn_Ok.Text = Resources.Common_Save;
            btn_Ok.Click += btn_Ok_Click;

            // LockIdTextEdit
            LockIdTextEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "LockId", true));
            LockIdTextEdit.Location = new System.Drawing.Point(142, 12);
            LockIdTextEdit.Name = "LockIdTextEdit";
            LockIdTextEdit.Size = new System.Drawing.Size(486, 20);
            LockIdTextEdit.StyleController = dataLayoutControl1;

            // DocumentTypeTextEdit
            DocumentTypeTextEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "DocumentType", true));
            DocumentTypeTextEdit.Location = new System.Drawing.Point(142, 36);
            DocumentTypeTextEdit.Name = "DocumentTypeTextEdit";
            DocumentTypeTextEdit.Size = new System.Drawing.Size(486, 20);
            DocumentTypeTextEdit.StyleController = dataLayoutControl1;

            // DocumentIdTextEdit
            DocumentIdTextEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "DocumentId", true));
            DocumentIdTextEdit.Location = new System.Drawing.Point(142, 60);
            DocumentIdTextEdit.Name = "DocumentIdTextEdit";
            DocumentIdTextEdit.Size = new System.Drawing.Size(486, 20);
            DocumentIdTextEdit.StyleController = dataLayoutControl1;

            // LockedByUserIdTextEdit
            LockedByUserIdTextEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "LockedByUserId", true));
            LockedByUserIdTextEdit.Location = new System.Drawing.Point(142, 84);
            LockedByUserIdTextEdit.Name = "LockedByUserIdTextEdit";
            LockedByUserIdTextEdit.Size = new System.Drawing.Size(486, 20);
            LockedByUserIdTextEdit.StyleController = dataLayoutControl1;

            // LockedByUserNameTextEdit
            LockedByUserNameTextEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "LockedByUserName", true));
            LockedByUserNameTextEdit.Location = new System.Drawing.Point(142, 108);
            LockedByUserNameTextEdit.Name = "LockedByUserNameTextEdit";
            LockedByUserNameTextEdit.Size = new System.Drawing.Size(486, 20);
            LockedByUserNameTextEdit.StyleController = dataLayoutControl1;

            // LockedAtUtcDateEdit
            LockedAtUtcDateEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "LockedAtUtc", true));
            LockedAtUtcDateEdit.Location = new System.Drawing.Point(142, 132);
            LockedAtUtcDateEdit.Name = "LockedAtUtcDateEdit";
            LockedAtUtcDateEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            LockedAtUtcDateEdit.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            LockedAtUtcDateEdit.Size = new System.Drawing.Size(486, 20);
            LockedAtUtcDateEdit.StyleController = dataLayoutControl1;

            // LastHeartbeatAtUtcDateEdit
            LastHeartbeatAtUtcDateEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "LastHeartbeatAtUtc", true));
            LastHeartbeatAtUtcDateEdit.Location = new System.Drawing.Point(142, 156);
            LastHeartbeatAtUtcDateEdit.Name = "LastHeartbeatAtUtcDateEdit";
            LastHeartbeatAtUtcDateEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            LastHeartbeatAtUtcDateEdit.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            LastHeartbeatAtUtcDateEdit.Size = new System.Drawing.Size(486, 20);
            LastHeartbeatAtUtcDateEdit.StyleController = dataLayoutControl1;

            // MachineNameTextEdit
            MachineNameTextEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "MachineName", true));
            MachineNameTextEdit.Location = new System.Drawing.Point(142, 180);
            MachineNameTextEdit.Name = "MachineNameTextEdit";
            MachineNameTextEdit.Size = new System.Drawing.Size(486, 20);
            MachineNameTextEdit.StyleController = dataLayoutControl1;

            // AppInstanceIdTextEdit
            AppInstanceIdTextEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "AppInstanceId", true));
            AppInstanceIdTextEdit.Location = new System.Drawing.Point(142, 204);
            AppInstanceIdTextEdit.Name = "AppInstanceIdTextEdit";
            AppInstanceIdTextEdit.Size = new System.Drawing.Size(486, 20);
            AppInstanceIdTextEdit.StyleController = dataLayoutControl1;

            // ReasonMemoEdit
            ReasonMemoEdit.DataBindings.Add(new Binding("EditValue", documentLocksBindingSource, "Reason", true));
            ReasonMemoEdit.Location = new System.Drawing.Point(142, 228);
            ReasonMemoEdit.Name = "ReasonMemoEdit";
            ReasonMemoEdit.Size = new System.Drawing.Size(486, 94);
            ReasonMemoEdit.StyleController = dataLayoutControl1;

            // Root
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            Root.GroupBordersVisible = false;
            Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
                autoGeneratedGroup0, emptySpaceItem1, layoutControlItem2, layoutControlItem1});
            Root.Name = "Root";
            Root.Size = new System.Drawing.Size(640, 360);
            Root.TextVisible = false;

            // autoGeneratedGroup0
            autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
                ItemForLockId,
                ItemForDocumentType,
                ItemForDocumentId,
                ItemForLockedByUserId,
                ItemForLockedByUserName,
                ItemForLockedAtUtc,
                ItemForLastHeartbeatAtUtc,
                ItemForMachineName,
                ItemForAppInstanceId,
                ItemForReason
            });
            autoGeneratedGroup0.Location = new System.Drawing.Point(0, 0);
            autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            autoGeneratedGroup0.Size = new System.Drawing.Size(620, 314);
            autoGeneratedGroup0.TextVisible = false;

            // Items captions (Resource yoxdursa, plain string qalır)
            ItemForLockId.Control = LockIdTextEdit;
            ItemForLockId.Text = "LockId";
            ItemForLockId.Name = "ItemForLockId";

            ItemForDocumentType.Control = DocumentTypeTextEdit;
            ItemForDocumentType.Text = "DocumentType";
            ItemForDocumentType.Name = "ItemForDocumentType";

            ItemForDocumentId.Control = DocumentIdTextEdit;
            ItemForDocumentId.Text = "DocumentId";
            ItemForDocumentId.Name = "ItemForDocumentId";

            ItemForLockedByUserId.Control = LockedByUserIdTextEdit;
            ItemForLockedByUserId.Text = "LockedByUserId";
            ItemForLockedByUserId.Name = "ItemForLockedByUserId";

            ItemForLockedByUserName.Control = LockedByUserNameTextEdit;
            ItemForLockedByUserName.Text = "LockedByUserName";
            ItemForLockedByUserName.Name = "ItemForLockedByUserName";

            ItemForLockedAtUtc.Control = LockedAtUtcDateEdit;
            ItemForLockedAtUtc.Text = "LockedAtUtc";
            ItemForLockedAtUtc.Name = "ItemForLockedAtUtc";

            ItemForLastHeartbeatAtUtc.Control = LastHeartbeatAtUtcDateEdit;
            ItemForLastHeartbeatAtUtc.Text = "LastHeartbeatAtUtc";
            ItemForLastHeartbeatAtUtc.Name = "ItemForLastHeartbeatAtUtc";

            ItemForMachineName.Control = MachineNameTextEdit;
            ItemForMachineName.Text = "MachineName";
            ItemForMachineName.Name = "ItemForMachineName";

            ItemForAppInstanceId.Control = AppInstanceIdTextEdit;
            ItemForAppInstanceId.Text = "AppInstanceId";
            ItemForAppInstanceId.Name = "ItemForAppInstanceId";

            ItemForReason.Control = ReasonMemoEdit;
            ItemForReason.Text = "Reason";
            ItemForReason.Name = "ItemForReason";

            // bottom buttons row
            emptySpaceItem1.AllowHotTrack = false;
            emptySpaceItem1.Location = new System.Drawing.Point(0, 314);
            emptySpaceItem1.Name = "emptySpaceItem1";
            emptySpaceItem1.Size = new System.Drawing.Size(459, 26);

            layoutControlItem2.Control = btn_Cancel;
            layoutControlItem2.Location = new System.Drawing.Point(459, 314);
            layoutControlItem2.Name = "layoutControlItem2";
            layoutControlItem2.Size = new System.Drawing.Size(80, 26);
            layoutControlItem2.TextVisible = false;

            layoutControlItem1.Control = btn_Ok;
            layoutControlItem1.Location = new System.Drawing.Point(539, 314);
            layoutControlItem1.Name = "layoutControlItem1";
            layoutControlItem1.Size = new System.Drawing.Size(81, 26);
            layoutControlItem1.TextVisible = false;

            // Form
            AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new System.Drawing.Size(640, 360);
            Controls.Add(dataLayoutControl1);
            Name = "FormDocumentLock";
            Text = "DocumentLock";
            Load += FormDocumentLock_Load;

            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).EndInit();
            dataLayoutControl1.ResumeLayout(false);

            ((System.ComponentModel.ISupportInitialize)LockIdTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)DocumentTypeTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)DocumentIdTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)LockedByUserIdTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)LockedByUserNameTextEdit.Properties).EndInit();

            ((System.ComponentModel.ISupportInitialize)LockedAtUtcDateEdit.Properties.CalendarTimeProperties).EndInit();
            ((System.ComponentModel.ISupportInitialize)LockedAtUtcDateEdit.Properties).EndInit();

            ((System.ComponentModel.ISupportInitialize)LastHeartbeatAtUtcDateEdit.Properties.CalendarTimeProperties).EndInit();
            ((System.ComponentModel.ISupportInitialize)LastHeartbeatAtUtcDateEdit.Properties).EndInit();

            ((System.ComponentModel.ISupportInitialize)MachineNameTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)AppInstanceIdTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)ReasonMemoEdit.Properties).EndInit();

            ((System.ComponentModel.ISupportInitialize)documentLocksBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)Root).EndInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).EndInit();

            ((System.ComponentModel.ISupportInitialize)ItemForLockId).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDocumentType).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForDocumentId).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForLockedByUserId).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForLockedByUserName).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForLockedAtUtc).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForLastHeartbeatAtUtc).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForMachineName).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForAppInstanceId).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForReason).EndInit();

            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).EndInit();

            ResumeLayout(false);
        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private DevExpress.XtraEditors.SimpleButton btn_Cancel;
        private DevExpress.XtraEditors.SimpleButton btn_Ok;

        private System.Windows.Forms.BindingSource documentLocksBindingSource;

        private DevExpress.XtraEditors.TextEdit LockIdTextEdit;
        private DevExpress.XtraEditors.TextEdit DocumentTypeTextEdit;
        private DevExpress.XtraEditors.TextEdit DocumentIdTextEdit;
        private DevExpress.XtraEditors.TextEdit LockedByUserIdTextEdit;
        private DevExpress.XtraEditors.TextEdit LockedByUserNameTextEdit;
        private DevExpress.XtraEditors.DateEdit LockedAtUtcDateEdit;
        private DevExpress.XtraEditors.DateEdit LastHeartbeatAtUtcDateEdit;
        private DevExpress.XtraEditors.TextEdit MachineNameTextEdit;
        private DevExpress.XtraEditors.TextEdit AppInstanceIdTextEdit;
        private DevExpress.XtraEditors.MemoEdit ReasonMemoEdit;

        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;

        private DevExpress.XtraLayout.LayoutControlItem ItemForLockId;
        private DevExpress.XtraLayout.LayoutControlItem ItemForDocumentType;
        private DevExpress.XtraLayout.LayoutControlItem ItemForDocumentId;
        private DevExpress.XtraLayout.LayoutControlItem ItemForLockedByUserId;
        private DevExpress.XtraLayout.LayoutControlItem ItemForLockedByUserName;
        private DevExpress.XtraLayout.LayoutControlItem ItemForLockedAtUtc;
        private DevExpress.XtraLayout.LayoutControlItem ItemForLastHeartbeatAtUtc;
        private DevExpress.XtraLayout.LayoutControlItem ItemForMachineName;
        private DevExpress.XtraLayout.LayoutControlItem ItemForAppInstanceId;
        private DevExpress.XtraLayout.LayoutControlItem ItemForReason;

        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
    }
}