using Foxoft.Models.Entity.Report;
using Foxoft.Properties;

namespace Foxoft
{
    partial class FormFormReport
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            dataLayoutControl1 = new DevExpress.XtraDataLayout.DataLayoutControl();
            btn_Cancel = new DevExpress.XtraEditors.SimpleButton();
            btn_Ok = new DevExpress.XtraEditors.SimpleButton();
            FormCodeLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            trFormReportsBindingSource = new BindingSource(components);
            ReportIdLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            ShortcutTextEdit = new DevExpress.XtraEditors.TextEdit();
            UseReportAsLookUpEdit = new DevExpress.XtraEditors.LookUpEdit();
            Root = new DevExpress.XtraLayout.LayoutControlGroup();
            autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            ItemForFormCode = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForReportId = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForShortcut = new DevExpress.XtraLayout.LayoutControlItem();
            ItemForUseReportAs = new DevExpress.XtraLayout.LayoutControlItem();
            emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
            layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).BeginInit();
            dataLayoutControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)FormCodeLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)trFormReportsBindingSource).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ReportIdLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ShortcutTextEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)UseReportAsLookUpEdit.Properties).BeginInit();
            ((System.ComponentModel.ISupportInitialize)Root).BeginInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForFormCode).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForReportId).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForShortcut).BeginInit();
            ((System.ComponentModel.ISupportInitialize)ItemForUseReportAs).BeginInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).BeginInit();
            SuspendLayout();
            // 
            // dataLayoutControl1
            // 
            dataLayoutControl1.Controls.Add(btn_Cancel);
            dataLayoutControl1.Controls.Add(btn_Ok);
            dataLayoutControl1.Controls.Add(FormCodeLookUpEdit);
            dataLayoutControl1.Controls.Add(ReportIdLookUpEdit);
            dataLayoutControl1.Controls.Add(ShortcutTextEdit);
            dataLayoutControl1.Controls.Add(UseReportAsLookUpEdit);
            dataLayoutControl1.DataSource = trFormReportsBindingSource;
            dataLayoutControl1.Dock = DockStyle.Fill;
            dataLayoutControl1.Location = new Point(0, 0);
            dataLayoutControl1.Name = "dataLayoutControl1";
            dataLayoutControl1.OptionsFocus.MoveFocusRightToLeft = false;
            dataLayoutControl1.Root = Root;
            dataLayoutControl1.Size = new Size(520, 170);
            dataLayoutControl1.TabIndex = 0;
            dataLayoutControl1.Text = "dataLayoutControl1";
            // 
            // btn_Cancel
            // 
            btn_Cancel.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Cancel.Location = new Point(348, 136);
            btn_Cancel.Name = "btn_Cancel";
            btn_Cancel.Size = new Size(77, 22);
            btn_Cancel.StyleController = dataLayoutControl1;
            btn_Cancel.TabIndex = 99;
            btn_Cancel.Text = Resources.Common_Cancel;
            btn_Cancel.Click += btn_Cancel_Click;
            // 
            // btn_Ok
            // 
            btn_Ok.ImageOptions.Location = DevExpress.XtraEditors.ImageLocation.MiddleCenter;
            btn_Ok.Location = new Point(429, 136);
            btn_Ok.Name = "btn_Ok";
            btn_Ok.Size = new Size(79, 22);
            btn_Ok.StyleController = dataLayoutControl1;
            btn_Ok.TabIndex = 100;
            btn_Ok.Text = Resources.Common_Save;
            btn_Ok.Click += btn_Ok_Click;
            // 
            // FormCodeLookUpEdit
            // 
            FormCodeLookUpEdit.DataBindings.Add(new Binding("EditValue", trFormReportsBindingSource, "FormCode", true));
            FormCodeLookUpEdit.Location = new Point(116, 12);
            FormCodeLookUpEdit.Name = "FormCodeLookUpEdit";
            FormCodeLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            FormCodeLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("FormCode", Resources.Entity_Form_Code), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("FormDesc", Resources.Entity_Form_Desc) });
            FormCodeLookUpEdit.Properties.DisplayMember = "FormDesc";
            FormCodeLookUpEdit.Properties.NullText = "";
            FormCodeLookUpEdit.Properties.ValueMember = "FormCode";
            FormCodeLookUpEdit.Size = new Size(392, 20);
            FormCodeLookUpEdit.StyleController = dataLayoutControl1;
            FormCodeLookUpEdit.TabIndex = 0;
            // 
            // trFormReportsBindingSource
            // 
            trFormReportsBindingSource.DataSource = typeof(TrFormReport);
            // 
            // ReportIdLookUpEdit
            // 
            ReportIdLookUpEdit.DataBindings.Add(new Binding("EditValue", trFormReportsBindingSource, "ReportId", true));
            ReportIdLookUpEdit.Location = new Point(116, 36);
            ReportIdLookUpEdit.Name = "ReportIdLookUpEdit";
            ReportIdLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            ReportIdLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("ReportId", Resources.Entity_Report_Id), new DevExpress.XtraEditors.Controls.LookUpColumnInfo("ReportName", Resources.Entity_Report_Name) });
            ReportIdLookUpEdit.Properties.DisplayMember = "ReportName";
            ReportIdLookUpEdit.Properties.NullText = "";
            ReportIdLookUpEdit.Properties.ValueMember = "ReportId";
            ReportIdLookUpEdit.Size = new Size(392, 20);
            ReportIdLookUpEdit.StyleController = dataLayoutControl1;
            ReportIdLookUpEdit.TabIndex = 1;
            // 
            // ShortcutTextEdit
            // 
            ShortcutTextEdit.DataBindings.Add(new Binding("EditValue", trFormReportsBindingSource, "Shortcut", true));
            ShortcutTextEdit.Location = new Point(116, 60);
            ShortcutTextEdit.Name = "ShortcutTextEdit";
            ShortcutTextEdit.Size = new Size(392, 20);
            ShortcutTextEdit.StyleController = dataLayoutControl1;
            ShortcutTextEdit.TabIndex = 2;
            // 
            // UseReportAsLookUpEdit
            // 
            UseReportAsLookUpEdit.DataBindings.Add(new Binding("EditValue", trFormReportsBindingSource, "UseReportAs", true));
            UseReportAsLookUpEdit.Location = new Point(116, 84);
            UseReportAsLookUpEdit.Name = "UseReportAsLookUpEdit";
            UseReportAsLookUpEdit.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
            UseReportAsLookUpEdit.Properties.Columns.AddRange(new DevExpress.XtraEditors.Controls.LookUpColumnInfo[] { new DevExpress.XtraEditors.Controls.LookUpColumnInfo("UseReportAsDesc", Resources.Entity_FormReport_UseReportAs) });
            UseReportAsLookUpEdit.Properties.DisplayMember = "UseReportAsDesc";
            UseReportAsLookUpEdit.Properties.NullText = "";
            UseReportAsLookUpEdit.Properties.ValueMember = "UseReportAs";
            UseReportAsLookUpEdit.Size = new Size(392, 20);
            UseReportAsLookUpEdit.StyleController = dataLayoutControl1;
            UseReportAsLookUpEdit.TabIndex = 3;
            // 
            // Root
            // 
            Root.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            Root.GroupBordersVisible = false;
            Root.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { autoGeneratedGroup0 });
            Root.Name = "Root";
            Root.Size = new Size(520, 170);
            Root.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            autoGeneratedGroup0.AllowDrawBackground = false;
            autoGeneratedGroup0.GroupBordersVisible = false;
            autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] { ItemForFormCode, ItemForReportId, ItemForShortcut, ItemForUseReportAs, emptySpaceItem1, layoutControlItem2, layoutControlItem1 });
            autoGeneratedGroup0.Location = new Point(0, 0);
            autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            autoGeneratedGroup0.Size = new Size(500, 150);
            // 
            // ItemForFormCode
            // 
            ItemForFormCode.Control = FormCodeLookUpEdit;
            ItemForFormCode.Location = new Point(0, 0);
            ItemForFormCode.Name = "ItemForFormCode";
            ItemForFormCode.Size = new Size(500, 24);
            ItemForFormCode.Text = Resources.Entity_FormReport_FormCode;
            ItemForFormCode.TextSize = new Size(92, 13);
            // 
            // ItemForReportId
            // 
            ItemForReportId.Control = ReportIdLookUpEdit;
            ItemForReportId.Location = new Point(0, 24);
            ItemForReportId.Name = "ItemForReportId";
            ItemForReportId.Size = new Size(500, 24);
            ItemForReportId.Text = Resources.Entity_FormReport_ReportId;
            ItemForReportId.TextSize = new Size(92, 13);
            // 
            // ItemForShortcut
            // 
            ItemForShortcut.Control = ShortcutTextEdit;
            ItemForShortcut.Location = new Point(0, 48);
            ItemForShortcut.Name = "ItemForShortcut";
            ItemForShortcut.Size = new Size(500, 24);
            ItemForShortcut.Text = Resources.Entity_FormReport_Shortcut;
            ItemForShortcut.TextSize = new Size(92, 13);
            // 
            // ItemForUseReportAs
            // 
            ItemForUseReportAs.Control = UseReportAsLookUpEdit;
            ItemForUseReportAs.Location = new Point(0, 72);
            ItemForUseReportAs.Name = "ItemForUseReportAs";
            ItemForUseReportAs.Size = new Size(500, 24);
            ItemForUseReportAs.Text = Resources.Entity_FormReport_UseReportAs;
            ItemForUseReportAs.TextSize = new Size(92, 13);
            // 
            // emptySpaceItem1
            // 
            emptySpaceItem1.Location = new Point(0, 96);
            emptySpaceItem1.Name = "emptySpaceItem1";
            emptySpaceItem1.Size = new Size(336, 54);
            // 
            // layoutControlItem2
            // 
            layoutControlItem2.Control = btn_Cancel;
            layoutControlItem2.Location = new Point(336, 96);
            layoutControlItem2.Name = "layoutControlItem2";
            layoutControlItem2.Size = new Size(81, 54);
            layoutControlItem2.TextVisible = false;
            // 
            // layoutControlItem1
            // 
            layoutControlItem1.Control = btn_Ok;
            layoutControlItem1.Location = new Point(417, 96);
            layoutControlItem1.Name = "layoutControlItem1";
            layoutControlItem1.Size = new Size(83, 54);
            layoutControlItem1.TextVisible = false;
            // 
            // FormFormReport
            // 
            AutoScaleDimensions = new SizeF(6F, 13F);
            AutoScaleMode = AutoScaleMode.Font;
            AutoValidate = AutoValidate.EnableAllowFocusChange;
            ClientSize = new Size(520, 170);
            Controls.Add(dataLayoutControl1);
            Name = "FormFormReport";
            StartPosition = FormStartPosition.CenterScreen;
            Text = Resources.Entity_FormReport;
            Load += FormFormReport_Load;
            ((System.ComponentModel.ISupportInitialize)dataLayoutControl1).EndInit();
            dataLayoutControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)FormCodeLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)trFormReportsBindingSource).EndInit();
            ((System.ComponentModel.ISupportInitialize)ReportIdLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)ShortcutTextEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)UseReportAsLookUpEdit.Properties).EndInit();
            ((System.ComponentModel.ISupportInitialize)Root).EndInit();
            ((System.ComponentModel.ISupportInitialize)autoGeneratedGroup0).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForFormCode).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForReportId).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForShortcut).EndInit();
            ((System.ComponentModel.ISupportInitialize)ItemForUseReportAs).EndInit();
            ((System.ComponentModel.ISupportInitialize)emptySpaceItem1).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem2).EndInit();
            ((System.ComponentModel.ISupportInitialize)layoutControlItem1).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayoutControl1;
        private BindingSource trFormReportsBindingSource;
        private DevExpress.XtraLayout.LayoutControlGroup Root;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraEditors.SimpleButton btn_Cancel;
        private DevExpress.XtraEditors.SimpleButton btn_Ok;
        private DevExpress.XtraEditors.LookUpEdit FormCodeLookUpEdit;
        private DevExpress.XtraEditors.LookUpEdit ReportIdLookUpEdit;
        private DevExpress.XtraEditors.TextEdit ShortcutTextEdit;
        private DevExpress.XtraEditors.LookUpEdit UseReportAsLookUpEdit;
        private DevExpress.XtraLayout.LayoutControlItem ItemForFormCode;
        private DevExpress.XtraLayout.LayoutControlItem ItemForReportId;
        private DevExpress.XtraLayout.LayoutControlItem ItemForShortcut;
        private DevExpress.XtraLayout.LayoutControlItem ItemForUseReportAs;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem1;
        private DevExpress.XtraLayout.LayoutControlItem layoutControlItem2;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
    }
}
